import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

function p(type: string, extras: string[] = []): string {
  const base: Record<string, any[]> = {
    BOURSE: [
      {nom:"Lettre de motivation",type:"lettre",categorie:"generable",obligatoire:true},
      {nom:"CV",type:"cv",categorie:"generable",obligatoire:true},
      {nom:"Relevés de notes",type:"releves",categorie:"personnel",obligatoire:true},
    ],
    EMPLOI: [
      {nom:"Lettre de motivation",type:"lettre",categorie:"generable",obligatoire:true},
      {nom:"CV",type:"cv",categorie:"generable",obligatoire:true},
    ],
    ADMISSION: [
      {nom:"Lettre de motivation",type:"lettre",categorie:"generable",obligatoire:true},
      {nom:"Relevés de notes",type:"releves",categorie:"personnel",obligatoire:true},
      {nom:"Diplômes",type:"diplome",categorie:"personnel",obligatoire:true},
    ],
    CONCOURS: [
      {nom:"Diplômes",type:"diplome",categorie:"personnel",obligatoire:true},
      {nom:"Acte de naissance",type:"etat_civil",categorie:"personnel",obligatoire:true},
    ],
  };
  const arr = [...(base[type] || base.EMPLOI)];
  for (const e of extras) {
    const map: Record<string,any> = {
      recommandation:{nom:"Lettres de recommandation",type:"recommandation",categorie:"personnel",obligatoire:true},
      passeport:{nom:"Passeport",type:"passeport",categorie:"personnel",obligatoire:true},
      langue:{nom:"Certificat de langue",type:"langue",categorie:"personnel",obligatoire:true},
      projet:{nom:"Projet de recherche",type:"projet",categorie:"generable",obligatoire:true},
      medical:{nom:"Certificat médical",type:"medical",categorie:"personnel",obligatoire:true},
      nationalite:{nom:"Certificat de nationalité",type:"nationalite",categorie:"personnel",obligatoire:true},
      casier:{nom:"Casier judiciaire",type:"casier",categorie:"personnel",obligatoire:true},
      photo:{nom:"Photo d identité",type:"photo",categorie:"personnel",obligatoire:true},
      diplome:{nom:"Diplômes certifiés",type:"diplome",categorie:"personnel",obligatoire:true},
      portfolio:{nom:"Portfolio",type:"portfolio",categorie:"personnel",obligatoire:true},
    };
    if (map[e]) arr.push(map[e]);
  }
  return JSON.stringify(arr);
}

type O = {
  type: string; source: string; organisme: string; intitule: string;
  description: string; langueDetectee: string; conditions: string;
  piecesExigees: string; exigenceLangue: string; dateLimite: string;
  lien: string; canalCandidature: string; cibleCandidature: string;
};

const ALL: O[] = [

// ═══ BOURSES SUPPLÉMENTAIRES — PAYS NORDIQUES & EUROPE ═══
{type:"BOURSE",source:"lund.se",organisme:"Lund University",intitule:"Bourse Lund University Global 2027 — Suède",description:"Bourses couvrant 25 à 100% des frais de scolarité pour master à Lund, une des meilleures universités scandinaves. Sciences, ingénierie, droit, lettres.",langueDetectee:"fr",conditions:"Être étudiant non-européen admis en master. Excellence académique.",piecesExigees:p("BOURSE"),exigenceLangue:"Anglais (IELTS 6.5+)",dateLimite:"2027-01-15",lien:"https://www.lunduniversity.lu.se/admissions/scholarships-and-awards",canalCandidature:"lien_info",cibleCandidature:"https://www.lunduniversity.lu.se/admissions/scholarships-and-awards"},
{type:"BOURSE",source:"uu.se",organisme:"Uppsala University",intitule:"Bourse Uppsala University 2027 — Suède",description:"Bourses pour étudiants non-européens en master à Uppsala, plus ancienne université de Scandinavie (1477). Exemptions de frais partielles ou totales.",langueDetectee:"fr",conditions:"Admis en master à Uppsala. Non-européen.",piecesExigees:p("BOURSE"),exigenceLangue:"Anglais (IELTS 6.5+)",dateLimite:"2027-01-15",lien:"https://www.uu.se/en/admissions/scholarships/",canalCandidature:"lien_info",cibleCandidature:"https://www.uu.se/en/admissions/scholarships/"},
{type:"BOURSE",source:"kth.se",organisme:"KTH Royal Institute of Technology",intitule:"Bourse KTH 2027 — Ingénierie Suède",description:"Bourses pour master en ingénierie à KTH Stockholm. Exemption des frais pour étudiants non-européens. KTH est la 1re école d'ingénieur de Suède.",langueDetectee:"fr",conditions:"Admis en master à KTH. Non-européen. Excellence académique.",piecesExigees:p("BOURSE"),exigenceLangue:"Anglais (IELTS 6.5+ ou TOEFL 90+)",dateLimite:"2027-01-15",lien:"https://www.kth.se/en/studies/fees-and-scholarships/",canalCandidature:"lien_info",cibleCandidature:"https://www.kth.se/en/studies/fees-and-scholarships/"},
{type:"BOURSE",source:"helsinki.fi",organisme:"University of Helsinki",intitule:"Bourse Helsinki 2027 — Finlande",description:"Bourses pour master à l'Université d'Helsinki, meilleure université de Finlande. Exemption totale des frais et allocation de 10 000 EUR/an.",langueDetectee:"fr",conditions:"Admis en master. Non-européen. Excellent dossier académique.",piecesExigees:p("BOURSE"),exigenceLangue:"Anglais (IELTS 6.5+)",dateLimite:"2027-01-10",lien:"https://www.helsinki.fi/en/admissions-and-education/apply-bachelors-and-masters-programmes/scholarships",canalCandidature:"lien_info",cibleCandidature:"https://www.helsinki.fi/en/admissions-and-education/apply-bachelors-and-masters-programmes/scholarships"},
{type:"BOURSE",source:"aalto.fi",organisme:"Aalto University",intitule:"Bourse Aalto University 2027 — Finlande",description:"Bourses pour master à Aalto (ex Helsinki University of Technology). Forte en design, technologie, commerce. Exemption de frais et allocation possible.",langueDetectee:"fr",conditions:"Admis en master. Non-européen. Top académique.",piecesExigees:p("BOURSE"),exigenceLangue:"Anglais (IELTS 6.5+)",dateLimite:"2027-01-10",lien:"https://www.aalto.fi/en/admission-services/scholarships-and-tuition-fee-waivers",canalCandidature:"lien_info",cibleCandidature:"https://www.aalto.fi/en/admission-services/scholarships-and-tuition-fee-waivers"},
{type:"BOURSE",source:"ntnu.no",organisme:"NTNU — Norwegian University of Science and Technology",intitule:"Études gratuites en Norvège — NTNU 2027",description:"La Norvège offre des études gratuites à tous les étudiants, y compris internationaux. NTNU à Trondheim est la 1re université technique. Seule une petite contribution semestrielle est demandée.",langueDetectee:"fr",conditions:"Être admis à NTNU. Prouver un financement suffisant pour le séjour (environ 137 000 NOK/an).",piecesExigees:p("BOURSE"),exigenceLangue:"Anglais (IELTS 6.5+) pour les masters en anglais",dateLimite:"2027-04-15",lien:"https://www.ntnu.edu/studies/tuition-fees",canalCandidature:"lien_info",cibleCandidature:"https://www.ntnu.edu/studies/tuition-fees"},
{type:"BOURSE",source:"uio.no",organisme:"University of Oslo",intitule:"Études gratuites — Université d'Oslo 2027",description:"L'Université d'Oslo, n°1 en Norvège, offre des études gratuites pour tous. Masters en anglais dans de nombreux domaines : droit, sciences, informatique, médecine.",langueDetectee:"fr",conditions:"Être admis à un master. Prouver un financement suffisant pour le visa.",piecesExigees:p("BOURSE"),exigenceLangue:"Anglais (IELTS 6.5+)",dateLimite:"2027-04-15",lien:"https://www.uio.no/english/studies/admission/master/",canalCandidature:"lien_info",cibleCandidature:"https://www.uio.no/english/studies/admission/master/"},
{type:"BOURSE",source:"dtu.dk",organisme:"DTU — Technical University of Denmark",intitule:"Bourse DTU 2027 — Ingénierie Danemark",description:"Bourses pour étudiants non-européens en master d'ingénierie à DTU. Exemption des frais et allocation mensuelle. DTU est la meilleure école technique du Danemark.",langueDetectee:"fr",conditions:"Admis en master à DTU. Non-européen. Excellence en ingénierie.",piecesExigees:p("BOURSE"),exigenceLangue:"Anglais (IELTS 6.5+)",dateLimite:"2027-01-15",lien:"https://www.dtu.dk/english/education/msc/tuition-fees-and-terms-of-payment/scholarships",canalCandidature:"lien_info",cibleCandidature:"https://www.dtu.dk/english/education/msc/tuition-fees-and-terms-of-payment/scholarships"},
{type:"BOURSE",source:"tu-delft.nl",organisme:"TU Delft",intitule:"Bourse TU Delft Excellence 2027 — Pays-Bas",description:"Bourses pour master à TU Delft, meilleure université technique des Pays-Bas. Couverture des frais et allocation mensuelle. Forte en génie civil, aérospatial et informatique.",langueDetectee:"fr",conditions:"Admis en master à TU Delft. Non-européen. Top 10% de la promotion.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais (IELTS 6.5+)",dateLimite:"2026-12-01",lien:"https://www.tudelft.nl/en/education/practical-matters/scholarships/",canalCandidature:"formulaire",cibleCandidature:"https://www.tudelft.nl/en/education/practical-matters/scholarships/"},
{type:"BOURSE",source:"uva.nl",organisme:"University of Amsterdam",intitule:"Bourse Amsterdam Excellence 2027",description:"Bourses pour master à l'Université d'Amsterdam, meilleure université des Pays-Bas. 25 000 EUR pour un an. Sciences, lettres, commerce, droit.",langueDetectee:"fr",conditions:"Admis en master à UvA. Non-européen. Résultats académiques exceptionnels.",piecesExigees:p("BOURSE"),exigenceLangue:"Anglais (IELTS 7.0+)",dateLimite:"2027-01-15",lien:"https://www.uva.nl/en/education/fees-and-funding/scholarships-and-loans/scholarships-and-loans.html",canalCandidature:"lien_info",cibleCandidature:"https://www.uva.nl/en/education/fees-and-funding/scholarships-and-loans/scholarships-and-loans.html"},
{type:"BOURSE",source:"wur.nl",organisme:"Wageningen University",intitule:"Bourse AFW Wageningen 2027 — Agriculture",description:"Bourses Africa Fellowship pour master à Wageningen, n°1 mondial en agriculture et alimentation. Frais de scolarité et allocation pour étudiants africains.",langueDetectee:"fr",conditions:"Être citoyen africain. Admis en master à Wageningen. Domaines : agriculture, alimentation, environnement.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais (IELTS 6.0+)",dateLimite:"2027-02-01",lien:"https://www.wur.nl/en/education-programmes/master/funding-your-studies.htm",canalCandidature:"formulaire",cibleCandidature:"https://www.wur.nl/en/education-programmes/master/funding-your-studies.htm"},
{type:"BOURSE",source:"ugent.be",organisme:"Ghent University",intitule:"Bourse Ghent University International Master 2027",description:"Bourses pour étudiants de pays en développement en master à Ghent University, top 100 mondial. Exemption des frais et allocation.",langueDetectee:"fr",conditions:"Admis en master à UGent. Pays en développement. Résultats académiques solides.",piecesExigees:p("BOURSE"),exigenceLangue:"Anglais (IELTS 6.5+)",dateLimite:"2027-03-01",lien:"https://www.ugent.be/en/research/funding/devcoop/scholarships.htm",canalCandidature:"lien_info",cibleCandidature:"https://www.ugent.be/en/research/funding/devcoop/scholarships.htm"},

// ═══ BOURSES SUPPLÉMENTAIRES — ASIE ═══
{type:"BOURSE",source:"nus.edu.sg",organisme:"National University of Singapore",intitule:"Bourse NUS ASEAN 2027 — Singapour",description:"Bourses pour étudiants internationaux à NUS, meilleure université d'Asie. Frais de scolarité, allocation et hébergement. Programmes en anglais.",langueDetectee:"fr",conditions:"Admis à NUS. Excellence académique et leadership.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais (IELTS 6.5+ ou TOEFL 85+)",dateLimite:"2027-01-15",lien:"https://www.nus.edu.sg/oam/scholarships/",canalCandidature:"formulaire",cibleCandidature:"https://www.nus.edu.sg/oam/scholarships/"},
{type:"BOURSE",source:"ntu.edu.sg",organisme:"Nanyang Technological University",intitule:"Bourse NTU 2027 — Singapour",description:"Bourses pour master et doctorat à NTU Singapour, top 15 mondial. Forte en ingénierie, IA et nanotechnologies. Frais et allocation couverts.",langueDetectee:"fr",conditions:"Admis à NTU. Résultats académiques compétitifs.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais (IELTS 6.5+)",dateLimite:"2027-01-31",lien:"https://www.ntu.edu.sg/admissions/graduate/financialmatters/scholarships",canalCandidature:"formulaire",cibleCandidature:"https://www.ntu.edu.sg/admissions/graduate/financialmatters/scholarships"},
{type:"BOURSE",source:"kaist.ac.kr",organisme:"KAIST",intitule:"Bourse KAIST 2027 — Corée du Sud Tech",description:"Bourses complètes pour master/doctorat à KAIST, MIT de la Corée du Sud. Frais de scolarité, allocation de 350 000 KRW/mois. Programmes en anglais en ingénierie et sciences.",langueDetectee:"fr",conditions:"Admis à KAIST. Non-coréen. Excellence en sciences ou ingénierie.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais (TOEFL 80+ ou IELTS 6.5+)",dateLimite:"2027-03-15",lien:"https://www.kaist.ac.kr/en/html/study/01.html",canalCandidature:"formulaire",cibleCandidature:"https://www.kaist.ac.kr/en/html/study/01.html"},
{type:"BOURSE",source:"keio.ac.jp",organisme:"Keio University",intitule:"Bourse Keio University 2027 — Japon privée",description:"Bourses pour étudiants internationaux à Keio, plus ancienne université privée du Japon. Programmes en anglais. Réduction de frais et allocation.",langueDetectee:"fr",conditions:"Admis à Keio. Non-japonais.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais ou japonais",dateLimite:"2027-02-28",lien:"https://www.keio.ac.jp/en/admissions/financial-aid/",canalCandidature:"lien_info",cibleCandidature:"https://www.keio.ac.jp/en/admissions/financial-aid/"},
{type:"BOURSE",source:"waseda.jp",organisme:"Waseda University",intitule:"Bourse Waseda University 2027 — Japon",description:"Bourses pour étudiants internationaux à Waseda, une des meilleures universités privées japonaises. Programmes en anglais en sciences politiques, commerce et ingénierie.",langueDetectee:"fr",conditions:"Admis à Waseda. Non-japonais. Bons résultats.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais (IELTS 6.0+) ou japonais",dateLimite:"2027-03-15",lien:"https://www.waseda.jp/inst/cie/en/from-overseas/scholarships",canalCandidature:"lien_info",cibleCandidature:"https://www.waseda.jp/inst/cie/en/from-overseas/scholarships"},
{type:"BOURSE",source:"ait.ac.th",organisme:"Asian Institute of Technology",intitule:"Bourse AIT 2027 — Thaïlande",description:"Bourses pour master et doctorat à l'AIT en Thaïlande. Domaines : ingénierie, environnement, management. Programmes en anglais. Campus international à Bangkok.",langueDetectee:"fr",conditions:"Licence ou master. Résortissant d'un pays en développement.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais (IELTS 5.5+)",dateLimite:"2027-04-30",lien:"https://www.ait.ac.th/admissions/scholarships/",canalCandidature:"formulaire",cibleCandidature:"https://www.ait.ac.th/admissions/scholarships/"},
{type:"BOURSE",source:"iitb.ac.in",organisme:"IIT Bombay",intitule:"Bourse IIT Bombay 2027 — Inde",description:"Bourses pour étudiants internationaux en master/doctorat à IIT Bombay, meilleur institut de technologie d'Inde. Allocation et exemption de frais.",langueDetectee:"fr",conditions:"Licence en ingénierie ou sciences. Non-indien. Résultats compétitifs.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais",dateLimite:"2027-04-15",lien:"https://www.iitb.ac.in/en/education/international-students",canalCandidature:"formulaire",cibleCandidature:"https://www.iitb.ac.in/en/education/international-students"},

// ═══ BOURSES USA SUPPLÉMENTAIRES ═══
{type:"BOURSE",source:"columbia.edu",organisme:"Columbia University",intitule:"Bourse Columbia University Fellowship 2027 — New York",description:"Bourses pour doctorat à Columbia University, Ivy League à New York. Financement complet pour 5 ans : frais, allocation et assurance. Toutes disciplines.",langueDetectee:"fr",conditions:"Admis en doctorat à Columbia. Excellence académique exceptionnelle.",piecesExigees:p("BOURSE",["recommandation","langue"]),exigenceLangue:"Anglais (TOEFL 100+ ou IELTS 7.0+)",dateLimite:"2026-12-15",lien:"https://gsas.columbia.edu/financial-aid",canalCandidature:"formulaire",cibleCandidature:"https://gsas.columbia.edu/financial-aid"},
{type:"BOURSE",source:"yale.edu",organisme:"Yale University",intitule:"Bourse Yale Graduate Fellowship 2027",description:"Bourses complètes pour doctorat à Yale, Ivy League. 5 ans de financement : frais de scolarité, allocation et assurance santé.",langueDetectee:"fr",conditions:"Admis en doctorat à Yale. Résultats académiques exceptionnels.",piecesExigees:p("BOURSE",["recommandation","langue"]),exigenceLangue:"Anglais (TOEFL 100+ ou IELTS 7.0+)",dateLimite:"2026-12-15",lien:"https://gsas.yale.edu/admissions/financial-aid",canalCandidature:"formulaire",cibleCandidature:"https://gsas.yale.edu/admissions/financial-aid"},
{type:"BOURSE",source:"upenn.edu",organisme:"University of Pennsylvania",intitule:"Bourse Penn Graduate Fellowship 2027",description:"Bourses pour doctorat à UPenn, Ivy League à Philadelphie. Financement complet. Forte en business (Wharton), médecine, droit et ingénierie.",langueDetectee:"fr",conditions:"Admis en doctorat à Penn. Excellence académique.",piecesExigees:p("BOURSE",["recommandation","langue"]),exigenceLangue:"Anglais (TOEFL 100+)",dateLimite:"2026-12-15",lien:"https://www.upenn.edu/graduate-studies",canalCandidature:"formulaire",cibleCandidature:"https://www.upenn.edu/graduate-studies"},
{type:"BOURSE",source:"cornell.edu",organisme:"Cornell University",intitule:"Bourse Cornell Graduate Fellowship 2027",description:"Bourses pour doctorat à Cornell, Ivy League. Financement complet incluant frais, allocation et assurance. Forte en agriculture, ingénierie et hôtellerie.",langueDetectee:"fr",conditions:"Admis en doctorat à Cornell. Résultats exceptionnels.",piecesExigees:p("BOURSE",["recommandation","langue"]),exigenceLangue:"Anglais (IELTS 7.0+ ou TOEFL 100+)",dateLimite:"2027-01-02",lien:"https://gradschool.cornell.edu/financial-support/",canalCandidature:"formulaire",cibleCandidature:"https://gradschool.cornell.edu/financial-support/"},
{type:"BOURSE",source:"uchicago.edu",organisme:"University of Chicago",intitule:"Bourse Chicago Graduate Fellowship 2027",description:"Bourses pour doctorat à l'Université de Chicago, top 10 mondial. Financement de 5 ans. Forte en économie, physique, sociologie et droit.",langueDetectee:"fr",conditions:"Admis en doctorat. Excellence académique et recherche.",piecesExigees:p("BOURSE",["recommandation","langue"]),exigenceLangue:"Anglais (TOEFL 100+ ou IELTS 7.0+)",dateLimite:"2026-12-15",lien:"https://grad.uchicago.edu/financial-aid/",canalCandidature:"formulaire",cibleCandidature:"https://grad.uchicago.edu/financial-aid/"},
{type:"BOURSE",source:"caltech.edu",organisme:"Caltech",intitule:"Bourse Caltech Graduate 2027 — Sciences & Ingénierie",description:"Bourses pour doctorat au California Institute of Technology. Financement complet pour tous les doctorants admis. Meilleur ratio étudiants/professeurs au monde.",langueDetectee:"fr",conditions:"Admis en doctorat à Caltech. Excellence exceptionnelle en sciences ou ingénierie.",piecesExigees:p("BOURSE",["recommandation","langue"]),exigenceLangue:"Anglais (TOEFL 100+)",dateLimite:"2026-12-15",lien:"https://www.caltech.edu/about/financial-support",canalCandidature:"formulaire",cibleCandidature:"https://www.caltech.edu/about/financial-support"},
{type:"BOURSE",source:"berkeley.edu",organisme:"UC Berkeley",intitule:"Bourse UC Berkeley International 2027",description:"Bourses pour master et doctorat à UC Berkeley, meilleure université publique au monde. Forte en informatique, ingénierie, politique publique.",langueDetectee:"fr",conditions:"Admis à Berkeley. Excellence académique. GRE souvent requis.",piecesExigees:p("BOURSE",["recommandation","langue"]),exigenceLangue:"Anglais (TOEFL 90+ ou IELTS 7.0+)",dateLimite:"2026-12-01",lien:"https://grad.berkeley.edu/financial/",canalCandidature:"formulaire",cibleCandidature:"https://grad.berkeley.edu/financial/"},

// ═══ BOURSES AFRIQUE ═══
{type:"BOURSE",source:"pau.edu.ng",organisme:"Pan-African University",intitule:"Bourse Union Africaine — Pan-African University 2027",description:"Bourses complètes pour master et doctorat dans les 5 instituts de la Pan-African University. Financé par l'UA. Sites : Nigeria, Kenya, Cameroun, Algérie, Afrique du Sud.",langueDetectee:"fr",conditions:"Être citoyen africain. Licence ou master selon le cycle. Moins de 35 ans.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais ou français selon l'institut",dateLimite:"2027-04-30",lien:"https://pau.africa/",canalCandidature:"formulaire",cibleCandidature:"https://pau.africa/"},
{type:"BOURSE",source:"aims.ac.za",organisme:"AIMS (African Institute for Mathematical Sciences)",intitule:"Bourse AIMS 2027 — Master Mathématiques Afrique",description:"Bourses complètes pour un master en sciences mathématiques dans un centre AIMS (Afrique du Sud, Ghana, Cameroun, Sénégal, Rwanda, Tanzanie). Bourse entièrement couverte.",langueDetectee:"fr",conditions:"Être citoyen africain. Licence en mathématiques, physique ou ingénierie. Moins de 32 ans.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais ou français selon le centre",dateLimite:"2027-03-15",lien:"https://nexteinstein.org/",canalCandidature:"formulaire",cibleCandidature:"https://nexteinstein.org/"},
{type:"BOURSE",source:"acbf-pact.org",organisme:"African Capacity Building Foundation",intitule:"Bourse ACBF 2027 — Renforcement des capacités",description:"Bourses pour des formations spécialisées en Afrique : gouvernance économique, gestion des finances publiques, politique commerciale. Pour professionnels africains.",langueDetectee:"fr",conditions:"Être un professionnel africain. Minimum 3 ans d'expérience dans le secteur public ou privé.",piecesExigees:p("BOURSE"),exigenceLangue:"Anglais ou français",dateLimite:"2027-05-31",lien:"https://www.acbf-pact.org/",canalCandidature:"lien_info",cibleCandidature:"https://www.acbf-pact.org/"},

// ═══ EMPLOI — TECH MONDE ═══
{type:"EMPLOI",source:"nvidia.com",organisme:"NVIDIA",intitule:"NVIDIA — Graduate Software Engineer 2027",description:"Postes pour diplômés chez NVIDIA, leader des GPU et de l'IA. Domaines : deep learning, conduite autonome, computing graphique. Bureaux mondiaux.",langueDetectee:"fr",conditions:"Master en informatique, IA ou génie électrique. Compétences en CUDA, Python ou C++.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-05-31",lien:"https://www.nvidia.com/en-us/about-nvidia/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.nvidia.com/en-us/about-nvidia/careers/"},
{type:"EMPLOI",source:"tesla.com",organisme:"Tesla",intitule:"Tesla — Engineering Graduate Program 2027",description:"Postes pour ingénieurs diplômés chez Tesla. Domaines : véhicules électriques, batteries, énergie solaire, IA, robotique. Usines aux USA, Allemagne (Berlin), Chine.",langueDetectee:"fr",conditions:"Master en génie mécanique, électrique, informatique ou matériaux. Passion pour l'énergie durable.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-05-31",lien:"https://www.tesla.com/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.tesla.com/careers"},
{type:"EMPLOI",source:"ibm.com",organisme:"IBM",intitule:"IBM — Entry Level & Graduate 2027",description:"Postes pour jeunes diplômés chez IBM. Domaines : consulting, cloud, cybersécurité, quantum computing, IA Watson. Présence dans 175 pays.",langueDetectee:"fr",conditions:"Licence ou master en informatique, ingénierie, mathématiques ou commerce.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-06-30",lien:"https://www.ibm.com/careers/entry-level/",canalCandidature:"formulaire",cibleCandidature:"https://www.ibm.com/careers/entry-level/"},
{type:"EMPLOI",source:"intel.com",organisme:"Intel Corporation",intitule:"Intel — Graduate Program 2027",description:"Postes pour diplômés chez Intel, leader des semi-conducteurs. Domaines : conception de puces, IA, cloud, 5G. Sites en USA, Irlande, Israël, Allemagne.",langueDetectee:"fr",conditions:"Master en génie électrique, informatique, physique ou mathématiques.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-05-31",lien:"https://www.intel.com/content/www/us/en/jobs/students-graduates.html",canalCandidature:"formulaire",cibleCandidature:"https://www.intel.com/content/www/us/en/jobs/students-graduates.html"},
{type:"EMPLOI",source:"cisco.com",organisme:"Cisco Systems",intitule:"Cisco — Early in Career 2027",description:"Postes pour jeunes diplômés chez Cisco, leader des réseaux et de la cybersécurité. Programmes d'ingénierie, ventes et conseil. Bureaux mondiaux.",langueDetectee:"fr",conditions:"Licence ou master en informatique, réseaux ou cybersécurité. Certification Cisco appréciée.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-05-31",lien:"https://jobs.cisco.com/jobs/BrowseJobs",canalCandidature:"formulaire",cibleCandidature:"https://jobs.cisco.com/jobs/BrowseJobs"},
{type:"EMPLOI",source:"oracle.com",organisme:"Oracle",intitule:"Oracle — Graduate Development Program 2027",description:"Programme pour diplômés chez Oracle, leader des bases de données et du cloud enterprise. 2 ans avec formation et rotations. Postes tech et consulting.",langueDetectee:"fr",conditions:"Master en informatique, ingénierie ou commerce. Compétences en SQL, Java ou cloud.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://www.oracle.com/careers/students-and-grads/",canalCandidature:"formulaire",cibleCandidature:"https://www.oracle.com/careers/students-and-grads/"},
{type:"EMPLOI",source:"spotify.com",organisme:"Spotify",intitule:"Spotify — Graduate Engineer 2027",description:"Postes pour ingénieurs diplômés chez Spotify. Travail sur la recommandation musicale, machine learning, infrastructure backend. Bureaux à Stockholm, NYC, Londres.",langueDetectee:"fr",conditions:"Master en informatique ou data science. Compétences en Python, Java ou Scala.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://www.lifeatspotify.com/students",canalCandidature:"formulaire",cibleCandidature:"https://www.lifeatspotify.com/students"},
{type:"EMPLOI",source:"stripe.com",organisme:"Stripe",intitule:"Stripe — New Graduate Software Engineer 2027",description:"Postes pour nouveaux diplômés chez Stripe, leader des paiements en ligne. Travail sur l'infrastructure financière mondiale. Bureaux à San Francisco, Dublin, Singapour.",langueDetectee:"fr",conditions:"Licence ou master en informatique. Solides compétences en algorithmique et systèmes distribués.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-03-31",lien:"https://stripe.com/jobs",canalCandidature:"formulaire",cibleCandidature:"https://stripe.com/jobs"},

// ═══ EMPLOI — BANQUES & FINANCE AFRIQUE ═══
{type:"EMPLOI",source:"ecobank.com",organisme:"Ecobank",intitule:"Ecobank — Postes Afrique de l'Ouest 2027",description:"Postes chez Ecobank, banque panafricaine présente dans 33 pays africains. Domaines : banque de détail, corporate banking, trésorerie, digital banking. Siège à Lomé.",langueDetectee:"fr",conditions:"Diplôme en finance, économie, comptabilité ou informatique. Expérience bancaire appréciée.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français et/ou anglais",dateLimite:"2027-06-30",lien:"https://www.ecobank.com/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.ecobank.com/careers"},
{type:"EMPLOI",source:"boa.africa",organisme:"Bank of Africa (BOA)",intitule:"BOA — Recrutements Afrique de l'Ouest 2027",description:"Postes chez Bank of Africa, groupe bancaire présent dans 17 pays africains. Domaines : crédit, trade finance, opérations, IT. Siège à Bamako, agences au Bénin.",langueDetectee:"fr",conditions:"Diplôme en finance, banque, économie ou informatique.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant",dateLimite:"2027-06-30",lien:"https://www.boa.africa/carriere",canalCandidature:"lien_info",cibleCandidature:"https://www.boa.africa/carriere"},
{type:"EMPLOI",source:"orabank.net",organisme:"Orabank",intitule:"Orabank — Postes Bénin et UEMOA 2027",description:"Postes chez Orabank, banque présente dans 12 pays d'Afrique de l'Ouest et Centrale. Domaines : banque de détail, PME, digital, conformité. Agences au Bénin.",langueDetectee:"fr",conditions:"Diplôme en finance, banque ou gestion. Connaissance du marché bancaire UEMOA.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant",dateLimite:"2027-06-30",lien:"https://www.orabank.net/carrieres/",canalCandidature:"formulaire",cibleCandidature:"https://www.orabank.net/carrieres/"},
{type:"EMPLOI",source:"bgfibank.com",organisme:"BGFIBank",intitule:"BGFIBank — Postes Afrique Centrale et Ouest 2027",description:"Postes chez BGFIBank, 1er groupe bancaire d'Afrique Centrale. Présent au Gabon, Congo, Cameroun, Côte d'Ivoire, Sénégal, RDC. Banque privée et corporate.",langueDetectee:"fr",conditions:"Diplôme en finance, économie ou informatique. Expérience en banque appréciée.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant",dateLimite:"2027-06-30",lien:"https://www.bgfi.com/carrieres/",canalCandidature:"lien_info",cibleCandidature:"https://www.bgfi.com/carrieres/"},
{type:"EMPLOI",source:"attijariwafabank.com",organisme:"Attijariwafa Bank",intitule:"Attijariwafa Bank — Postes Afrique 2027",description:"Postes chez Attijariwafa Bank, 1er groupe bancaire du Maghreb et 3e en Afrique. Présent dans 25 pays africains. Domaines : retail, corporate, banque d'investissement.",langueDetectee:"fr",conditions:"Diplôme en finance, commerce ou IT. Connaissance du marché africain.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant, arabe apprécié",dateLimite:"2027-06-30",lien:"https://www.attijariwafabank.com/fr/carrieres",canalCandidature:"formulaire",cibleCandidature:"https://www.attijariwafabank.com/fr/carrieres"},

// ═══ EMPLOI — INDUSTRIE & ÉNERGIE AFRIQUE ═══
{type:"EMPLOI",source:"dangote.com",organisme:"Dangote Group",intitule:"Dangote — Postes Afrique de l'Ouest 2027",description:"Postes chez Dangote, plus grand conglomérat industriel d'Afrique. Domaines : ciment, pétrochimie, sucre, sel, agriculture. Usines au Nigeria, Bénin, Ghana, Sénégal.",langueDetectee:"fr",conditions:"Diplôme en ingénierie, chimie, commerce ou logistique. Expérience industrielle appréciée.",piecesExigees:p("EMPLOI"),exigenceLangue:"Anglais courant, français apprécié",dateLimite:"2027-06-30",lien:"https://www.dangote.com/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.dangote.com/careers/"},
{type:"EMPLOI",source:"lafargeholcim-benin.com",organisme:"Holcim Bénin (ex LafargeHolcim)",intitule:"Holcim Bénin — Postes 2027",description:"Postes chez Holcim au Bénin, leader mondial des matériaux de construction. Domaines : production ciment, logistique, maintenance, HSE, ventes. Usine de Cotonou.",langueDetectee:"fr",conditions:"Diplôme en ingénierie des matériaux, génie civil, mécanique ou commerce.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant",dateLimite:"2027-06-30",lien:"https://www.holcim.com/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.holcim.com/careers"},
{type:"EMPLOI",source:"sococim.sn",organisme:"SOCOCIM Industries",intitule:"SOCOCIM — Postes Industrie Sénégal 2027",description:"Postes chez SOCOCIM Industries (filiale Vicat), cimenterie leader au Sénégal. Production, maintenance, qualité, logistique. Usine à Rufisque, Dakar.",langueDetectee:"fr",conditions:"Diplôme en génie mécanique, électrique, chimie ou production industrielle.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant",dateLimite:"2027-06-30",lien:"https://www.sococim.com/",canalCandidature:"lien_info",cibleCandidature:"https://www.sococim.com/"},

// ═══ EMPLOI — TÉLÉCOMS & TECH AFRIQUE ═══
{type:"EMPLOI",source:"mtn.com",organisme:"MTN Group",intitule:"MTN Group — Graduate Programme Afrique 2027",description:"Programme pour jeunes diplômés chez MTN, 1er opérateur télécoms d'Afrique. 2 ans de rotations dans les filiales africaines. Domaines : réseau, digital, mobile money.",langueDetectee:"fr",conditions:"Master récent. Maximum 28 ans. Leadership et innovation.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant, français apprécié",dateLimite:"2027-03-31",lien:"https://www.mtn.com/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.mtn.com/careers/"},
{type:"EMPLOI",source:"airtelafrica.com",organisme:"Airtel Africa",intitule:"Airtel Africa — Graduate Trainee 2027",description:"Programme trainee chez Airtel Africa. Présent dans 14 pays africains. Domaines : réseau mobile, Airtel Money, marketing, ventes, IT.",langueDetectee:"fr",conditions:"Master récent. Dynamisme et orientation résultats.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais et/ou français",dateLimite:"2027-04-30",lien:"https://www.airtel.africa/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.airtel.africa/careers"},
{type:"EMPLOI",source:"andela.com",organisme:"Andela",intitule:"Andela — Développeurs Afrique 2027",description:"Postes de développeurs logiciels chez Andela, plateforme connectant des talents tech africains avec des entreprises mondiales. Travail à distance. Full-stack, backend, mobile.",langueDetectee:"fr",conditions:"2+ ans d'expérience en développement logiciel. Maîtrise de React, Node.js, Python ou autre stack.",piecesExigees:p("EMPLOI"),exigenceLangue:"Anglais courant",dateLimite:"2027-06-30",lien:"https://andela.com/for-talent/",canalCandidature:"formulaire",cibleCandidature:"https://andela.com/for-talent/"},
{type:"EMPLOI",source:"flutterwave.com",organisme:"Flutterwave",intitule:"Flutterwave — Postes Fintech Afrique 2027",description:"Postes chez Flutterwave, licorne fintech africaine. Domaines : ingénierie logicielle, data, produit, opérations paiements. Bureaux au Nigeria, Kenya, Ghana.",langueDetectee:"fr",conditions:"Diplôme en informatique, finance ou commerce. Expérience fintech appréciée.",piecesExigees:p("EMPLOI"),exigenceLangue:"Anglais courant",dateLimite:"2027-06-30",lien:"https://flutterwave.com/us/careers",canalCandidature:"formulaire",cibleCandidature:"https://flutterwave.com/us/careers"},

// ═══ CONCOURS SUPPLÉMENTAIRES ═══
{type:"CONCOURS",source:"tresor.bj",organisme:"Direction Générale du Trésor — Bénin",intitule:"Concours Trésor Public Bénin 2026",description:"Concours de recrutement au Trésor public du Bénin. Grades : agent, contrôleur, inspecteur du Trésor. Gestion des finances publiques de l'État.",langueDetectee:"fr",conditions:"Nationalité béninoise. Diplôme requis selon le grade. Casier judiciaire vierge.",piecesExigees:p("CONCOURS",["nationalite","casier","photo"]),exigenceLangue:"Français",dateLimite:"2026-12-31",lien:"https://www.tresor.bj/",canalCandidature:"formulaire",cibleCandidature:"https://www.tresor.bj/"},
{type:"CONCOURS",source:"minfop.cm",organisme:"Fonction Publique Cameroun",intitule:"Concours Fonction Publique Cameroun 2026",description:"Concours de recrutement dans la fonction publique camerounaise. Administration générale, enseignement, santé, finances. Milliers de postes annuels.",langueDetectee:"fr",conditions:"Nationalité camerounaise. Diplôme requis selon la catégorie. Casier vierge.",piecesExigees:p("CONCOURS",["nationalite","casier","photo"]),exigenceLangue:"Français ou anglais",dateLimite:"2026-12-31",lien:"https://www.minfopra.gov.cm/",canalCandidature:"formulaire",cibleCandidature:"https://www.minfopra.gov.cm/"},
{type:"CONCOURS",source:"fonctionpublique.gouv.sn",organisme:"Fonction Publique Sénégal",intitule:"Concours Fonction Publique Sénégal 2026",description:"Concours de la fonction publique sénégalaise. Postes dans l'administration, la santé, l'éducation et les finances. Ouverts aux citoyens sénégalais.",langueDetectee:"fr",conditions:"Nationalité sénégalaise. Diplôme requis selon le corps. Maximum 35 ans.",piecesExigees:p("CONCOURS",["nationalite","casier","photo"]),exigenceLangue:"Français",dateLimite:"2026-12-31",lien:"https://www.fonctionpublique.gouv.sn/",canalCandidature:"formulaire",cibleCandidature:"https://www.fonctionpublique.gouv.sn/"},
{type:"CONCOURS",source:"mfp.tg",organisme:"Fonction Publique Togo",intitule:"Concours Fonction Publique Togo 2026",description:"Concours de la fonction publique togolaise. Administration, enseignement, santé, douanes. Pour citoyens togolais.",langueDetectee:"fr",conditions:"Nationalité togolaise. Diplôme requis selon la catégorie.",piecesExigees:p("CONCOURS",["nationalite","casier"]),exigenceLangue:"Français",dateLimite:"2026-12-31",lien:"https://www.mfpt.gouv.tg/",canalCandidature:"formulaire",cibleCandidature:"https://www.mfpt.gouv.tg/"},
{type:"CONCOURS",source:"fonctionpublique.gouv.ne",organisme:"Fonction Publique Niger",intitule:"Concours Fonction Publique Niger 2026",description:"Concours de la fonction publique nigérienne. Postes dans les ministères, l'éducation, la santé et les finances. Pour citoyens nigériens.",langueDetectee:"fr",conditions:"Nationalité nigérienne. Diplôme requis selon le grade.",piecesExigees:p("CONCOURS",["nationalite","casier"]),exigenceLangue:"Français",dateLimite:"2026-12-31",lien:"https://www.fonctionpublique.gouv.ne/",canalCandidature:"formulaire",cibleCandidature:"https://www.fonctionpublique.gouv.ne/"},
{type:"CONCOURS",source:"mfp.gov.bf",organisme:"Fonction Publique Burkina Faso",intitule:"Concours Fonction Publique Burkina Faso 2026",description:"Concours de la fonction publique burkinabè. Administration, enseignement, santé, justice. Pour citoyens du Burkina Faso.",langueDetectee:"fr",conditions:"Nationalité burkinabè. Diplôme requis selon le corps. Casier judiciaire vierge.",piecesExigees:p("CONCOURS",["nationalite","casier"]),exigenceLangue:"Français",dateLimite:"2026-12-31",lien:"https://www.fonction-publique.gov.bf/",canalCandidature:"formulaire",cibleCandidature:"https://www.fonction-publique.gov.bf/"},
{type:"CONCOURS",source:"fonctionpublique.gouv.ml",organisme:"Fonction Publique Mali",intitule:"Concours Fonction Publique Mali 2026",description:"Concours de la fonction publique malienne. Administration, enseignement, santé, sécurité. Pour citoyens maliens.",langueDetectee:"fr",conditions:"Nationalité malienne. Diplôme requis.",piecesExigees:p("CONCOURS",["nationalite","casier"]),exigenceLangue:"Français",dateLimite:"2026-12-31",lien:"https://www.fonctionpublique.gouv.ml/",canalCandidature:"formulaire",cibleCandidature:"https://www.fonctionpublique.gouv.ml/"},
{type:"CONCOURS",source:"fonctionpublique.gouv.gn",organisme:"Fonction Publique Guinée",intitule:"Concours Fonction Publique Guinée 2026",description:"Concours de la fonction publique guinéenne. Administration, enseignement, santé, mines. Pour citoyens guinéens.",langueDetectee:"fr",conditions:"Nationalité guinéenne. Diplôme requis.",piecesExigees:p("CONCOURS",["nationalite","casier"]),exigenceLangue:"Français",dateLimite:"2026-12-31",lien:"https://www.fonctionpublique.gov.gn/",canalCandidature:"formulaire",cibleCandidature:"https://www.fonctionpublique.gov.gn/"},
{type:"CONCOURS",source:"ensea.ed.ci",organisme:"ENSEA Côte d'Ivoire",intitule:"Concours ENSEA 2026-2027 — Statistiques Abidjan",description:"Concours d'entrée à l'ENSEA d'Abidjan, école de statistiques pour l'Afrique francophone. Formations d'ingénieurs statisticiens et de techniciens supérieurs.",langueDetectee:"fr",conditions:"Bac scientifique ou licence selon le cycle. Concours ouvert aux Africains francophones.",piecesExigees:p("CONCOURS",["diplome"]),exigenceLangue:"Français",dateLimite:"2026-09-15",lien:"https://www.ensea.ed.ci/",canalCandidature:"formulaire",cibleCandidature:"https://www.ensea.ed.ci/"},
{type:"CONCOURS",source:"enaref.bf",organisme:"ENAREF Burkina Faso",intitule:"Concours ENAREF 2026-2027 — Finances Ouagadougou",description:"Concours d'entrée à l'ENAREF (École Nationale des Régies Financières) de Ouagadougou. Formation des agents des impôts, douanes et trésor.",langueDetectee:"fr",conditions:"Bac+2 minimum. Concours ouvert aux Africains francophones. Conditions d'âge.",piecesExigees:p("CONCOURS",["diplome","nationalite"]),exigenceLangue:"Français",dateLimite:"2026-10-31",lien:"https://www.enaref.bf/",canalCandidature:"formulaire",cibleCandidature:"https://www.enaref.bf/"},
{type:"CONCOURS",source:"iia.edu.sn",organisme:"IIA Sénégal",intitule:"Concours IIA 2026-2027 — Assurances Dakar",description:"Concours d'entrée à l'Institut International des Assurances de Yaoundé et Dakar. Formation en assurance, actuariat, réassurance. Pour Africains francophones.",langueDetectee:"fr",conditions:"Licence en économie, gestion, mathématiques ou droit. Maximum 30 ans.",piecesExigees:p("CONCOURS",["diplome"]),exigenceLangue:"Français",dateLimite:"2026-10-15",lien:"https://www.iia-assurance.org/",canalCandidature:"formulaire",cibleCandidature:"https://www.iia-assurance.org/"},

// ═══ ADMISSION SUPPLÉMENTAIRES ═══
{type:"ADMISSION",source:"up.ac.za",organisme:"University of Pretoria",intitule:"Admission Master University of Pretoria 2027 — Afrique du Sud",description:"Candidature aux masters de l'Université de Pretoria, top 5 en Afrique. Programmes en anglais. Sciences, ingénierie, droit, médecine vétérinaire.",langueDetectee:"fr",conditions:"Licence pertinente. Résultats académiques compétitifs.",piecesExigees:p("ADMISSION",["langue"]),exigenceLangue:"Anglais (IELTS 6.5+)",dateLimite:"2027-08-31",lien:"https://www.up.ac.za/postgraduate/",canalCandidature:"formulaire",cibleCandidature:"https://www.up.ac.za/postgraduate/"},
{type:"ADMISSION",source:"uct.ac.za",organisme:"University of Cape Town",intitule:"Admission Master UCT 2027 — Afrique du Sud",description:"Candidature aux masters de UCT, meilleure université d'Afrique. Domaines variés : ingénierie, commerce (GSB), droit, médecine, sciences.",langueDetectee:"fr",conditions:"Licence avec de bons résultats. Procédure en ligne.",piecesExigees:p("ADMISSION",["langue"]),exigenceLangue:"Anglais (IELTS 6.5+)",dateLimite:"2027-07-31",lien:"https://www.uct.ac.za/apply/",canalCandidature:"formulaire",cibleCandidature:"https://www.uct.ac.za/apply/"},
{type:"ADMISSION",source:"wits.ac.za",organisme:"University of the Witwatersrand",intitule:"Admission Master Wits 2027 — Johannesburg",description:"Candidature aux masters de Wits à Johannesburg. Forte en ingénierie minière, santé publique, commerce et droit. Top 5 en Afrique.",langueDetectee:"fr",conditions:"Licence pertinente avec de bons résultats.",piecesExigees:p("ADMISSION",["langue"]),exigenceLangue:"Anglais (IELTS 6.0+)",dateLimite:"2027-09-30",lien:"https://www.wits.ac.za/postgraduate/",canalCandidature:"formulaire",cibleCandidature:"https://www.wits.ac.za/postgraduate/"},
{type:"ADMISSION",source:"um6p.ma",organisme:"Université Mohammed VI Polytechnique",intitule:"Admission Master UM6P 2027 — Ben Guerir, Maroc",description:"Candidature aux masters de l'UM6P, nouvelle université marocaine d'excellence. Domaines : mining, agriculture, data science, matériaux. Bourses disponibles.",langueDetectee:"fr",conditions:"Licence en sciences ou ingénierie. Dossier académique compétitif.",piecesExigees:p("ADMISSION",["recommandation"]),exigenceLangue:"Français ou anglais selon le programme",dateLimite:"2027-05-31",lien:"https://www.um6p.ma/en/admissions",canalCandidature:"formulaire",cibleCandidature:"https://www.um6p.ma/en/admissions"},
{type:"ADMISSION",source:"2ie-edu.org",organisme:"2iE Ouagadougou",intitule:"Admission Master 2iE 2027 — Eau et Énergie Burkina",description:"Candidature aux masters de l'Institut International d'Ingénierie de l'Eau et de l'Environnement à Ouagadougou. Eau, énergie, génie civil, environnement.",langueDetectee:"fr",conditions:"Licence en sciences, ingénierie ou environnement. Africains prioritaires.",piecesExigees:p("ADMISSION"),exigenceLangue:"Français",dateLimite:"2027-06-30",lien:"https://www.2ie-edu.org/",canalCandidature:"formulaire",cibleCandidature:"https://www.2ie-edu.org/"},
{type:"ADMISSION",source:"emi.um5.ac.ma",organisme:"EMI Rabat",intitule:"Admission Master EMI 2027 — Ingénierie Maroc",description:"Candidature aux masters de l'École Mohammadia d'Ingénieurs à Rabat. Génie civil, informatique, électrique, industriel. Ouverte aux étudiants africains.",langueDetectee:"fr",conditions:"Licence en sciences ou ingénierie. Résultats compétitifs.",piecesExigees:p("ADMISSION"),exigenceLangue:"Français",dateLimite:"2026-09-30",lien:"https://www.emi.ac.ma/",canalCandidature:"formulaire",cibleCandidature:"https://www.emi.ac.ma/"},
{type:"ADMISSION",source:"ucad.sn",organisme:"Université Cheikh Anta Diop (UCAD)",intitule:"Admission Master UCAD 2027 — Dakar, Sénégal",description:"Candidature aux masters de l'UCAD, plus grande université d'Afrique de l'Ouest francophone. Sciences, lettres, droit, médecine, économie.",langueDetectee:"fr",conditions:"Licence pertinente. Dossier de candidature complet.",piecesExigees:p("ADMISSION"),exigenceLangue:"Français",dateLimite:"2027-06-30",lien:"https://www.ucad.sn/",canalCandidature:"formulaire",cibleCandidature:"https://www.ucad.sn/"},
{type:"ADMISSION",source:"univ-cocody.ci",organisme:"Université Félix Houphouët-Boigny",intitule:"Admission Master UFHB 2027 — Abidjan, Côte d'Ivoire",description:"Candidature aux masters de l'UFHB d'Abidjan. Sciences, lettres, droit, économie, médecine. Plus grande université de Côte d'Ivoire.",langueDetectee:"fr",conditions:"Licence pertinente obtenue.",piecesExigees:p("ADMISSION"),exigenceLangue:"Français",dateLimite:"2027-06-30",lien:"https://www.univ-fhb.edu.ci/",canalCandidature:"formulaire",cibleCandidature:"https://www.univ-fhb.edu.ci/"},
{type:"ADMISSION",source:"uy1.uninet.cm",organisme:"Université de Yaoundé I",intitule:"Admission Master Yaoundé I 2027 — Cameroun",description:"Candidature aux masters de l'Université de Yaoundé I. Sciences, lettres, droit, sciences politiques. Bilingue français/anglais.",langueDetectee:"fr",conditions:"Licence pertinente. Candidature en ligne.",piecesExigees:p("ADMISSION"),exigenceLangue:"Français ou anglais",dateLimite:"2027-06-30",lien:"https://uy1.uninet.cm/",canalCandidature:"formulaire",cibleCandidature:"https://uy1.uninet.cm/"},

// ═══ EMPLOI — PHARMA & SANTÉ ═══
{type:"EMPLOI",source:"novartis.com",organisme:"Novartis",intitule:"Novartis — Graduate Programme 2027",description:"Programme pour diplômés chez Novartis, géant pharmaceutique suisse. 2 ans avec rotations en R&D, marketing, digital santé. Bureaux dans 140+ pays.",langueDetectee:"fr",conditions:"Master ou doctorat en pharmacie, biologie, chimie, data science ou commerce.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-03-31",lien:"https://www.novartis.com/careers/students-scholars",canalCandidature:"formulaire",cibleCandidature:"https://www.novartis.com/careers/students-scholars"},
{type:"EMPLOI",source:"roche.com",organisme:"Roche",intitule:"Roche — Graduate Trainee Programme 2027",description:"Programme trainee chez Roche, leader mondial de la pharma et diagnostics. 2 ans à Bâle (Suisse). Domaines : R&D, bioinformatique, diagnostics.",langueDetectee:"fr",conditions:"Master ou doctorat en sciences de la vie, pharmacie, informatique ou data science.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant, allemand apprécié",dateLimite:"2027-03-31",lien:"https://careers.roche.com/global/en/students-and-graduates",canalCandidature:"formulaire",cibleCandidature:"https://careers.roche.com/global/en/students-and-graduates"},
{type:"EMPLOI",source:"sanofi.com",organisme:"Sanofi",intitule:"Sanofi — Graduate Programme 2027",description:"Programme pour jeunes diplômés chez Sanofi, groupe pharma français. 2 ans avec rotations internationales. Domaines : R&D, production, digital, commercial.",langueDetectee:"fr",conditions:"Master en pharmacie, biologie, chimie, ingénierie ou commerce. 0-2 ans d'expérience.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais et français courants",dateLimite:"2027-04-30",lien:"https://www.sanofi.com/en/careers/students-graduates",canalCandidature:"formulaire",cibleCandidature:"https://www.sanofi.com/en/careers/students-graduates"},
{type:"EMPLOI",source:"pfizer.com",organisme:"Pfizer",intitule:"Pfizer — Graduate Programme 2027",description:"Programme pour diplômés chez Pfizer. Domaines : R&D, manufacturing, affaires réglementaires, digital. Bureaux en USA, UK et monde.",langueDetectee:"fr",conditions:"Master ou doctorat en sciences pharmaceutiques, chimie, biologie ou ingénierie.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://www.pfizer.com/about/careers/students-graduates",canalCandidature:"formulaire",cibleCandidature:"https://www.pfizer.com/about/careers/students-graduates"},
{type:"EMPLOI",source:"gsk.com",organisme:"GSK",intitule:"GSK — Future Leaders Programme 2027",description:"Programme de 2-3 ans chez GSK (GlaxoSmithKline). Rotations en R&D, production pharmaceutique, commercial et digital. Sites au UK, USA et mondial.",langueDetectee:"fr",conditions:"Master en sciences de la vie, pharmacie, chimie, ingénierie ou commerce.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-03-31",lien:"https://www.gsk.com/en-gb/careers/early-talent/",canalCandidature:"formulaire",cibleCandidature:"https://www.gsk.com/en-gb/careers/early-talent/"},

// ═══ EMPLOI — AUTOMOBILE & AÉRO ═══
{type:"EMPLOI",source:"mercedes-benz.com",organisme:"Mercedes-Benz",intitule:"Mercedes-Benz — Graduate Program 2027",description:"Programme pour jeunes diplômés chez Mercedes-Benz. 18 mois avec rotations. Domaines : ingénierie automobile, électromobilité, logiciel, design. Stuttgart.",langueDetectee:"fr",conditions:"Master en ingénierie, informatique ou commerce. Allemand et anglais courants.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Allemand et anglais courants",dateLimite:"2027-04-30",lien:"https://www.mercedes-benz.com/en/career/",canalCandidature:"formulaire",cibleCandidature:"https://www.mercedes-benz.com/en/career/"},
{type:"EMPLOI",source:"safran-group.com",organisme:"Safran",intitule:"Safran — Programme Graduate 2027 — Aéronautique",description:"Programme pour jeunes ingénieurs chez Safran, équipementier aéronautique français. Moteurs d'avion, systèmes d'atterrissage, optronique. Sites en France et mondial.",langueDetectee:"fr",conditions:"Master en ingénierie aérospatiale, mécanique ou matériaux. 0-3 ans d'expérience.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Français et anglais courants",dateLimite:"2027-04-30",lien:"https://www.safran-group.com/fr/nous-rejoindre",canalCandidature:"formulaire",cibleCandidature:"https://www.safran-group.com/fr/nous-rejoindre"},
{type:"EMPLOI",source:"thalesgroup.com",organisme:"Thales",intitule:"Thales — Graduate Programme 2027 — Défense et Tech",description:"Programme pour diplômés chez Thales, leader français de la défense, aérospatiale et cybersécurité. 2 ans avec rotations. Présence dans 68 pays.",langueDetectee:"fr",conditions:"Master en ingénierie, informatique ou cybersécurité. Habilitation possible.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Français et anglais courants",dateLimite:"2027-04-30",lien:"https://www.thalesgroup.com/en/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.thalesgroup.com/en/careers"},
{type:"EMPLOI",source:"dassault-aviation.com",organisme:"Dassault Aviation",intitule:"Dassault Aviation — Jeunes diplômés 2027",description:"Postes pour jeunes ingénieurs chez Dassault Aviation. Conception d'avions militaires (Rafale) et civils (Falcon). Ingénierie, production, essais en vol.",langueDetectee:"fr",conditions:"Master en ingénierie aérospatiale, mécanique ou informatique.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Français courant, anglais apprécié",dateLimite:"2027-05-31",lien:"https://www.dassault-aviation.com/fr/emplois/",canalCandidature:"formulaire",cibleCandidature:"https://www.dassault-aviation.com/fr/emplois/"},
{type:"EMPLOI",source:"valeo.com",organisme:"Valeo",intitule:"Valeo — Graduate Programme 2027 — Automobile",description:"Programme pour diplômés chez Valeo, équipementier automobile français. Systèmes de conduite autonome, électrification, éclairage. Sites mondiaux.",langueDetectee:"fr",conditions:"Master en ingénierie, informatique embarquée ou électronique.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant, français apprécié",dateLimite:"2027-05-31",lien:"https://www.valeo.com/en/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.valeo.com/en/careers/"},
{type:"EMPLOI",source:"michelin.com",organisme:"Michelin",intitule:"Michelin — VIE et Graduate 2027",description:"Postes VIE (Volontariat International en Entreprise) et graduate chez Michelin. Ingénierie des matériaux, production, R&D pneus. Sites en France et mondial.",langueDetectee:"fr",conditions:"Master en ingénierie des matériaux, chimie, mécanique ou commerce. 0-2 ans d'expérience.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Français et anglais",dateLimite:"2027-05-31",lien:"https://careers.michelin.com/",canalCandidature:"formulaire",cibleCandidature:"https://careers.michelin.com/"},

// ═══ EMPLOI — ÉNERGIE & CONSTRUCTION ═══
{type:"EMPLOI",source:"edf.fr",organisme:"EDF (Électricité de France)",intitule:"EDF — Graduate Programme 2027 — Énergie nucléaire et renouvelable",description:"Programme pour jeunes ingénieurs chez EDF. Nucléaire, hydraulique, solaire, éolien. 1er producteur d'électricité en Europe. Sites en France et UK.",langueDetectee:"fr",conditions:"Master en génie nucléaire, électrique, mécanique ou environnemental.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Français courant",dateLimite:"2027-04-30",lien:"https://www.edf.fr/edf-recrute/",canalCandidature:"formulaire",cibleCandidature:"https://www.edf.fr/edf-recrute/"},
{type:"EMPLOI",source:"vinci.com",organisme:"VINCI",intitule:"VINCI — Postes Génie Civil Afrique 2027",description:"Postes chez VINCI en Afrique. Construction de routes, ponts, barrages, aéroports. VINCI est le 1er groupe mondial de concessions et construction.",langueDetectee:"fr",conditions:"Diplôme en génie civil, géotechnique, BTP ou gestion de projet.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant, anglais apprécié",dateLimite:"2027-06-30",lien:"https://www.vinci.com/vinci.nsf/en/careers.htm",canalCandidature:"formulaire",cibleCandidature:"https://www.vinci.com/vinci.nsf/en/careers.htm"},
{type:"EMPLOI",source:"bouygues-construction.com",organisme:"Bouygues Construction",intitule:"Bouygues Construction — Postes Afrique 2027",description:"Postes d'ingénieurs et techniciens chez Bouygues Construction en Afrique. Bâtiment, travaux publics, génie civil. Projets majeurs au Bénin et Côte d'Ivoire.",langueDetectee:"fr",conditions:"Diplôme en génie civil, BTP, électricité ou mécanique.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant",dateLimite:"2027-06-30",lien:"https://www.bouygues-construction.com/carrieres/",canalCandidature:"formulaire",cibleCandidature:"https://www.bouygues-construction.com/carrieres/"},
{type:"EMPLOI",source:"shell.com",organisme:"Shell",intitule:"Shell — Graduate Programme 2027 — Énergie",description:"Programme pour diplômés chez Shell. 3-5 ans de développement. Domaines : ingénierie, géosciences, trading, finance, digital. Projets gaziers en Afrique.",langueDetectee:"fr",conditions:"Master en ingénierie, géosciences, physique, chimie ou commerce.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-03-31",lien:"https://www.shell.com/careers/students-and-graduates.html",canalCandidature:"formulaire",cibleCandidature:"https://www.shell.com/careers/students-and-graduates.html"},

// ═══ EMPLOI BÉNIN LOCAL ═══
{type:"EMPLOI",source:"boad.org",organisme:"BOAD (Banque Ouest Africaine de Développement)",intitule:"BOAD — Recrutements 2027 (Lomé)",description:"Postes à la BOAD à Lomé. Financement de projets de développement en UEMOA. Domaines : économie, finance, ingénierie de projets, environnement.",langueDetectee:"fr",conditions:"Master en économie, finance, ingénierie ou environnement. Citoyenneté UEMOA.",piecesExigees:p("EMPLOI",["diplome","nationalite"]),exigenceLangue:"Français courant",dateLimite:"2027-06-30",lien:"https://www.boad.org/recrutement/",canalCandidature:"formulaire",cibleCandidature:"https://www.boad.org/recrutement/"},
{type:"EMPLOI",source:"cotonou.bj",organisme:"Mairie de Cotonou",intitule:"Mairie de Cotonou — Recrutements 2027",description:"Postes à la Mairie de Cotonou. Administration municipale, urbanisme, assainissement, transport, culture. Service public local.",langueDetectee:"fr",conditions:"Diplôme pertinent. Nationalité béninoise.",piecesExigees:p("EMPLOI",["nationalite"]),exigenceLangue:"Français",dateLimite:"2027-06-30",lien:"https://www.cotonou.bj/",canalCandidature:"lien_info",cibleCandidature:"https://www.cotonou.bj/"},
{type:"EMPLOI",source:"asecna.org",organisme:"ASECNA",intitule:"ASECNA — Postes Navigation Aérienne Afrique 2027",description:"Postes à l'ASECNA, agence de la sécurité de la navigation aérienne en Afrique. Contrôle aérien, météo, télécommunications. 18 pays membres dont le Bénin.",langueDetectee:"fr",conditions:"Diplôme en aéronautique, météorologie, électronique ou télécommunications. Citoyenneté d'un État membre.",piecesExigees:p("EMPLOI",["diplome","nationalite"]),exigenceLangue:"Français courant, anglais aéronautique",dateLimite:"2027-06-30",lien:"https://www.asecna.aero/",canalCandidature:"formulaire",cibleCandidature:"https://www.asecna.aero/"},
{type:"EMPLOI",source:"agetip.bj",organisme:"AGETIP Bénin",intitule:"AGETIP Bénin — Postes Projets d'Infrastructure 2027",description:"Postes à l'AGETIP Bénin, agence d'exécution des travaux d'intérêt public. Gestion de projets d'infrastructure : routes, bâtiments scolaires, centres de santé.",langueDetectee:"fr",conditions:"Diplôme en génie civil, gestion de projet, architecture ou économie. Expérience terrain appréciée.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français",dateLimite:"2027-06-30",lien:"https://www.agetip.bj/",canalCandidature:"lien_info",cibleCandidature:"https://www.agetip.bj/"},

// ═══ BOURSES PROGRAMMES SPÉCIAUX ═══
{type:"BOURSE",source:"daad.de",organisme:"DAAD",intitule:"DAAD Helmut Schmidt Programme 2027 — Administration publique",description:"Bourses pour master en administration publique ou développement économique en Allemagne. Pour professionnels des pays en développement. 2 ans de financement complet.",langueDetectee:"fr",conditions:"Licence. 2+ ans d'expérience dans le secteur public. Engagement à retourner au pays.",piecesExigees:p("BOURSE",["recommandation","langue"]),exigenceLangue:"Anglais (IELTS 6.0+)",dateLimite:"2026-09-30",lien:"https://www.daad.de/en/studying-in-germany/scholarships/helmut-schmidt-programme/",canalCandidature:"formulaire",cibleCandidature:"https://www.daad.de/en/studying-in-germany/scholarships/helmut-schmidt-programme/"},
{type:"BOURSE",source:"chevening.org",organisme:"Foreign Office britannique",intitule:"Bourse Chevening Bénin 2027 — Master au UK",description:"Bourses Chevening spécifiquement pour les candidats béninois. Master d'un an au Royaume-Uni. Financement complet. Ouvre des portes dans le réseau Chevening mondial.",langueDetectee:"fr",conditions:"Être citoyen béninois résidant au Bénin. 2 ans d'expérience. S'engager à retourner au Bénin.",piecesExigees:p("BOURSE",["recommandation","langue"]),exigenceLangue:"Anglais (IELTS 6.5 minimum dans chaque section)",dateLimite:"2026-11-05",lien:"https://www.chevening.org/scholarships/",canalCandidature:"formulaire",cibleCandidature:"https://www.chevening.org/scholarships/"},
{type:"BOURSE",source:"cityu.edu.hk",organisme:"City University of Hong Kong",intitule:"Bourse CityU Hong Kong 2027",description:"Bourses pour master et doctorat à City University of Hong Kong. Forte en ingénierie, business et sciences. Environnement international anglophone.",langueDetectee:"fr",conditions:"Licence avec de bons résultats. Non-hongkongais.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais (IELTS 6.5+ ou TOEFL 79+)",dateLimite:"2027-04-30",lien:"https://www.cityu.edu.hk/sgs/prospective-students/admissions-scholarships",canalCandidature:"formulaire",cibleCandidature:"https://www.cityu.edu.hk/sgs/prospective-students/admissions-scholarships"},
{type:"BOURSE",source:"hku.hk",organisme:"University of Hong Kong",intitule:"Bourse HKU 2027 — Hong Kong",description:"Bourses pour master et doctorat à HKU, meilleure université de Hong Kong (top 30 mondial). Environnement multiculturel. Sciences, commerce, ingénierie.",langueDetectee:"fr",conditions:"Licence avec d'excellents résultats.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais (IELTS 6.0+ ou TOEFL 80+)",dateLimite:"2027-02-28",lien:"https://www.gradsch.hku.hk/gradsch/prospective-students/scholarships-fees-and-financial-support",canalCandidature:"formulaire",cibleCandidature:"https://www.gradsch.hku.hk/gradsch/prospective-students/scholarships-fees-and-financial-support"},

// ═══ EMPLOI — CONSULTING & SERVICES ═══
{type:"EMPLOI",source:"bain.com",organisme:"Bain & Company",intitule:"Bain & Company — Associate Consultant 2027",description:"Postes de consultant junior chez Bain, cabinet de conseil en stratégie top 3 mondial. Bureau de Johannesburg pour l'Afrique. Cas business et transformation.",langueDetectee:"fr",conditions:"Master d'une grande école ou université de premier plan. Excellence analytique.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://www.bain.com/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.bain.com/careers/"},
{type:"EMPLOI",source:"accenture.com",organisme:"Accenture",intitule:"Accenture — Graduate Programme Afrique 2027",description:"Programme pour diplômés chez Accenture en Afrique. Domaines : consulting, technologie, digital, opérations. Bureaux au Nigeria, Kenya, Afrique du Sud.",langueDetectee:"fr",conditions:"Master en informatique, ingénierie, commerce ou domaine connexe.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant, français apprécié",dateLimite:"2027-05-31",lien:"https://www.accenture.com/us-en/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.accenture.com/us-en/careers/"},
{type:"EMPLOI",source:"capgemini.com",organisme:"Capgemini",intitule:"Capgemini — Graduate Programme 2027",description:"Programme pour diplômés chez Capgemini, leader français du consulting et de la technologie. Domaines : cloud, cybersécurité, data, IA. 50+ pays.",langueDetectee:"fr",conditions:"Master en informatique, ingénierie ou commerce. 0-2 ans d'expérience.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Français et anglais courants",dateLimite:"2027-05-31",lien:"https://www.capgemini.com/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.capgemini.com/careers/"},
{type:"EMPLOI",source:"soprasteria.com",organisme:"Sopra Steria",intitule:"Sopra Steria — Jeunes Diplômés IT 2027",description:"Postes pour jeunes diplômés chez Sopra Steria, ESN française. Développement logiciel, conseil digital, cybersécurité. Sites en France et Europe.",langueDetectee:"fr",conditions:"Master en informatique, ingénierie ou mathématiques. Compétences en développement.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Français courant",dateLimite:"2027-06-30",lien:"https://www.soprasteria.com/en/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.soprasteria.com/en/careers"},
{type:"EMPLOI",source:"atos.net",organisme:"Atos / Eviden",intitule:"Atos Eviden — Graduate Programme 2027",description:"Programme pour diplômés chez Atos/Eviden, leader européen du numérique. Domaines : cloud, cybersécurité, HPC, décarbonation digitale. Présence en Afrique.",langueDetectee:"fr",conditions:"Master en informatique, cybersécurité ou ingénierie.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Français et anglais",dateLimite:"2027-05-31",lien:"https://eviden.com/careers/",canalCandidature:"formulaire",cibleCandidature:"https://eviden.com/careers/"},

// ═══ EMPLOI — AGROALIMENTAIRE ═══
{type:"EMPLOI",source:"cargill.com",organisme:"Cargill",intitule:"Cargill — Associate Programme Afrique 2027",description:"Programme pour diplômés chez Cargill en Afrique. Géant mondial de l'agroalimentaire. Commerce de matières premières, transformation, logistique. Présence en Côte d'Ivoire (cacao).",langueDetectee:"fr",conditions:"Master en agro-industrie, commerce, logistique ou ingénierie.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais et/ou français",dateLimite:"2027-04-30",lien:"https://careers.cargill.com/",canalCandidature:"formulaire",cibleCandidature:"https://careers.cargill.com/"},
{type:"EMPLOI",source:"olam.com",organisme:"Olam Group",intitule:"Olam — Management Trainee Afrique 2027",description:"Programme trainee chez Olam, leader mondial des matières premières agricoles. Cacao, café, coton, noix de cajou. Fort en Afrique de l'Ouest dont le Bénin.",langueDetectee:"fr",conditions:"Master en agro-industrie, commerce international ou logistique.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais et/ou français",dateLimite:"2027-05-31",lien:"https://www.olamgroup.com/careers.html",canalCandidature:"formulaire",cibleCandidature:"https://www.olamgroup.com/careers.html"},

// ═══ BOURSES — FORMATIONS PROFESSIONNELLES ═══
{type:"BOURSE",source:"idrc.ca",organisme:"CRDI Canada",intitule:"Bourse CRDI 2027 — Recherche pour le développement",description:"Bourses du Centre de Recherches pour le Développement International (CRDI) du Canada. Financement de recherche de master et doctorat liée au développement en Afrique.",langueDetectee:"fr",conditions:"Être inscrit en master ou doctorat. Sujet de recherche lié au développement. Citoyen d'un pays en développement.",piecesExigees:p("BOURSE",["recommandation","projet"]),exigenceLangue:"Français ou anglais",dateLimite:"2027-04-30",lien:"https://idrc.ca/en/funding",canalCandidature:"formulaire",cibleCandidature:"https://idrc.ca/en/funding"},
{type:"BOURSE",source:"codesria.org",organisme:"CODESRIA",intitule:"Bourse CODESRIA 2027 — Recherche en sciences sociales Afrique",description:"Bourses du Conseil pour le Développement de la Recherche en Sciences Sociales en Afrique. Petites subventions de recherche pour doctorants et chercheurs africains.",langueDetectee:"fr",conditions:"Être chercheur ou doctorant africain en sciences sociales ou humaines.",piecesExigees:p("BOURSE",["projet"]),exigenceLangue:"Français, anglais ou portugais",dateLimite:"2027-03-31",lien:"https://codesria.org/",canalCandidature:"formulaire",cibleCandidature:"https://codesria.org/"},

// ═══ ADMISSION — UNIVERSITÉS EN LIGNE / MOOC ═══
{type:"ADMISSION",source:"coursera.org",organisme:"University of Michigan (via Coursera)",intitule:"Master en ligne Applied Data Science — Michigan 2027",description:"Master en ligne en data science appliquée de l'University of Michigan via Coursera. 100% en ligne, flexible. Reconnu internationalement.",langueDetectee:"fr",conditions:"Licence dans un domaine STEM. Compétences en Python et statistiques.",piecesExigees:p("ADMISSION"),exigenceLangue:"Anglais",dateLimite:"2027-06-30",lien:"https://www.coursera.org/degrees/master-of-applied-data-science-umich",canalCandidature:"formulaire",cibleCandidature:"https://www.coursera.org/degrees/master-of-applied-data-science-umich"},
{type:"ADMISSION",source:"edx.org",organisme:"Georgia Tech (via edX)",intitule:"Online Master in Computer Science — Georgia Tech 2027",description:"Master en informatique en ligne de Georgia Tech via edX. Coût très abordable (~7 000 USD total). Spécialisations en IA, systèmes, computing interactif.",langueDetectee:"fr",conditions:"Licence en informatique ou domaine quantitatif. Expérience en programmation.",piecesExigees:p("ADMISSION"),exigenceLangue:"Anglais",dateLimite:"2027-03-01",lien:"https://omscs.gatech.edu/",canalCandidature:"formulaire",cibleCandidature:"https://omscs.gatech.edu/"},
];

async function main() {
  console.log(`Lot 2 — Total à insérer : ${ALL.length} opportunités`);
  let inserted = 0, skipped = 0;
  for (const o of ALL) {
    const exists = await prisma.opportunite.findFirst({
      where: { intitule: o.intitule, organisme: o.organisme },
    });
    if (exists) { skipped++; continue; }
    await prisma.opportunite.create({
      data: {
        type: o.type, source: o.source, organisme: o.organisme,
        intitule: o.intitule, description: o.description,
        langueDetectee: o.langueDetectee, conditions: o.conditions,
        piecesExigees: o.piecesExigees, exigenceLangue: o.exigenceLangue,
        dateLimite: new Date(o.dateLimite), lien: o.lien,
        canalCandidature: o.canalCandidature, cibleCandidature: o.cibleCandidature,
        statut: "publiee", actif: true, confianceDateLimite: 0.85,
        sourceDateLimite: "recherche web",
      },
    });
    inserted++;
    if (inserted % 50 === 0) console.log(`  ... ${inserted} insérées`);
  }
  const total = await prisma.opportunite.count({ where: { statut: "publiee" } });
  console.log(`\nInsérées : ${inserted} | Déjà existantes : ${skipped} | Total publiées : ${total}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
export {};
