import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

function p(t: string, e: string[] = []): string {
  const b: Record<string, any[]> = {
    BOURSE: [{nom:"Lettre de motivation",type:"lettre",categorie:"generable",obligatoire:true},{nom:"CV",type:"cv",categorie:"generable",obligatoire:true},{nom:"Relevés de notes",type:"releves",categorie:"personnel",obligatoire:true}],
    EMPLOI: [{nom:"Lettre de motivation",type:"lettre",categorie:"generable",obligatoire:true},{nom:"CV",type:"cv",categorie:"generable",obligatoire:true}],
    ADMISSION: [{nom:"Lettre de motivation",type:"lettre",categorie:"generable",obligatoire:true},{nom:"Relevés de notes",type:"releves",categorie:"personnel",obligatoire:true},{nom:"Diplômes",type:"diplome",categorie:"personnel",obligatoire:true}],
    CONCOURS: [{nom:"Diplômes",type:"diplome",categorie:"personnel",obligatoire:true},{nom:"Acte de naissance",type:"etat_civil",categorie:"personnel",obligatoire:true}],
  };
  const a=[...(b[t]||b.EMPLOI)];const m:Record<string,any>={recommandation:{nom:"Lettres de recommandation",type:"recommandation",categorie:"personnel",obligatoire:true},passeport:{nom:"Passeport",type:"passeport",categorie:"personnel",obligatoire:true},langue:{nom:"Certificat de langue",type:"langue",categorie:"personnel",obligatoire:true},projet:{nom:"Projet de recherche",type:"projet",categorie:"generable",obligatoire:true},medical:{nom:"Certificat médical",type:"medical",categorie:"personnel",obligatoire:true},nationalite:{nom:"Certificat de nationalité",type:"nationalite",categorie:"personnel",obligatoire:true},casier:{nom:"Casier judiciaire",type:"casier",categorie:"personnel",obligatoire:true},photo:{nom:"Photo d identité",type:"photo",categorie:"personnel",obligatoire:true},diplome:{nom:"Diplômes certifiés",type:"diplome",categorie:"personnel",obligatoire:true}};
  for(const x of e)if(m[x])a.push(m[x]);return JSON.stringify(a);
}

type O={type:string;source:string;organisme:string;intitule:string;description:string;langueDetectee:string;conditions:string;piecesExigees:string;exigenceLangue:string;dateLimite:string;lien:string;canalCandidature:string;cibleCandidature:string};

function mk(type:string,source:string,org:string,titre:string,desc:string,cond:string,lang:string,date:string,url:string,extras:string[]=[]): O {
  return {type,source,organisme:org,intitule:titre,description:desc,langueDetectee:"fr",conditions:cond,piecesExigees:p(type,extras),exigenceLangue:lang,dateLimite:date,lien:url,canalCandidature:"formulaire",cibleCandidature:url};
}

const E = (s:string,o:string,t:string,d:string,c:string,l:string,dt:string,u:string,x:string[]=[]) => mk("EMPLOI",s,o,t,d,c,l,dt,u,x);
const B = (s:string,o:string,t:string,d:string,c:string,l:string,dt:string,u:string,x:string[]=[]) => mk("BOURSE",s,o,t,d,c,l,dt,u,x);
const A = (s:string,o:string,t:string,d:string,c:string,l:string,dt:string,u:string,x:string[]=[]) => mk("ADMISSION",s,o,t,d,c,l,dt,u,x);
const C = (s:string,o:string,t:string,d:string,c:string,l:string,dt:string,u:string,x:string[]=[]) => mk("CONCOURS",s,o,t,d,c,l,dt,u,x);

const ALL: O[] = [
// ══════════════════════════════════════════════
// BLOC 1 — BOURSES SUPPLÉMENTAIRES (120 entrées)
// ══════════════════════════════════════════════

// --- Pays-Bas ---
B("uu.nl","Utrecht University","Bourse Utrecht Excellence 2027","Bourses pour master à Utrecht University. 15 000 à 30 000 EUR. Top 50 mondial. Sciences, droit, économie, informatique.","Admis en master à Utrecht. Non-européen. Excellence académique.","Anglais (IELTS 6.5+)","2027-02-01","https://www.uu.nl/en/masters/general-information/international-students/scholarships"),
B("rug.nl","University of Groningen","Bourse Groningen Eric Bleumink 2027","Bourse Eric Bleumink pour étudiants de pays en développement en master à Groningen. Frais + allocation mensuelle.","Admis en master à Groningen. Pays en développement. Excellent dossier.","Anglais (IELTS 6.5+)","2027-01-15","https://www.rug.nl/education/scholarships/eric-bleumink-fund",["recommandation"]),
B("leidenuniv.nl","Leiden University","Bourse Leiden Excellence 2027","Bourses LExS de 10 000 à 15 000 EUR pour master à Leiden. Plus ancienne université des Pays-Bas (1575).","Admis en master à Leiden. Non-européen.","Anglais (IELTS 6.5+)","2027-02-01","https://www.universiteitleiden.nl/en/scholarships"),
B("wur.nl","Wageningen University","Bourse Wageningen Africa 2027","Bourses pour étudiants africains en master à Wageningen. Sciences agricoles, alimentation, environnement. Top 1 mondial en agriculture.","Admis en master à Wageningen. Nationalité africaine.","Anglais (IELTS 6.0+)","2027-02-01","https://www.wur.nl/en/education-programmes/wageningen-university/msc-programmes/scholarships.htm",["recommandation"]),
B("maastrichtuniversity.nl","Maastricht University","Bourse Maastricht High Potential 2027","Bourses pour master à Maastricht. Problem-Based Learning. Business, droit européen, neurosciences, data science.","Admis en master à Maastricht. Non-européen. Top 5% de la promotion.","Anglais","2027-03-01","https://www.maastrichtuniversity.nl/support/your-studies-begin/scholarships"),

// --- Scandinavie ---
B("uu.se","Uppsala University","Bourse Uppsala IPK 2027","Bourses IPK pour étudiants de pays non-UE en master à Uppsala. Sciences, ingénierie, lettres. Plus ancienne université nordique (1477).","Admis en master à Uppsala. Non-européen.","Anglais (IELTS 6.5+)","2027-01-15","https://www.uu.se/en/study/scholarships"),
B("lu.se","Lund University","Bourse Lund Global 2027","Bourses pour étudiants internationaux en master à Lund. 25 à 100% des frais. Top 100 mondial.","Admis en master à Lund. Non-européen.","Anglais (IELTS 6.5+)","2027-01-15","https://www.lunduniversity.lu.se/international-admissions/scholarships-and-awards"),
B("helsinki.fi","University of Helsinki","Bourse Helsinki Master 2027","Bourses pour master à l'Université d'Helsinki. Exonération des frais et allocation de 10 000 EUR/an. Top 100 mondial.","Admis en master à Helsinki. Non-européen.","Anglais","2027-01-15","https://www.helsinki.fi/en/admissions-and-education/apply-bachelors-and-masters-programmes/scholarships"),
B("uio.no","University of Oslo","Bourse Oslo Master 2027","Master sans frais de scolarité à l'Université d'Oslo. Programmes en anglais en informatique, sciences, économie, droit. Norvège = pas de frais.","Admis en master à Oslo. Tous les étudiants (frais gratuits en Norvège pour tous).","Anglais (IELTS 6.5+)","2027-04-15","https://www.uio.no/english/studies/admission/"),
B("ku.dk","University of Copenhagen","Bourse Copenhague 2027","Bourses pour master à l'Université de Copenhague. Exonération des frais. Sciences, santé publique, informatique.","Admis en master à Copenhague. Non-européen.","Anglais","2027-01-15","https://studies.ku.dk/masters/scholarships/"),
B("dtu.dk","DTU","Bourse DTU Scholarships 2027","Bourses pour master en ingénierie à DTU (Technical University of Denmark). 7 500 à 35 000 DKK/mois. Top ingénierie nordique.","Admis en master à DTU. Non-européen.","Anglais","2027-01-15","https://www.dtu.dk/english/education/msc/scholarships"),

// --- Suisse ---
B("ethz.ch","ETH Zurich","Bourse ETH Zurich Excellence 2027","Bourses Excellence pour master à ETH Zurich, meilleure université d'Europe continentale. Allocation de 12 000 CHF/semestre.","Admis en master à ETH Zurich. GPA top 10%. Excellence exceptionnelle.","Anglais","2027-12-15","https://ethz.ch/students/en/studies/financial/scholarships.html",["recommandation"]),
B("epfl.ch","EPFL","Bourse EPFL Excellence Fellowship 2027","Bourses d'excellence pour master à l'EPFL. 16 000 CHF/an. Ingénierie, sciences, informatique. Lausanne.","Admis en master à l'EPFL. Excellence académique exceptionnelle.","Anglais ou français","2027-04-15","https://www.epfl.ch/education/master/admission/fees-and-financial-aid/",["recommandation"]),
B("unige.ch","Université de Genève","Bourse UNIGE Excellence Masters 2027","Bourses d'excellence pour master à l'Université de Genève. 10 000 à 15 000 CHF/an. Sciences, lettres, droit, SES.","Admis en master à l'UNIGE. Moyenne supérieure à 5/6.","Français ou anglais","2027-02-28","https://www.unige.ch/financements/"),
B("unil.ch","Université de Lausanne","Bourse UNIL Master 2027","Bourses pour étudiants internationaux en master à l'UNIL. 1 600 CHF/mois. Biologie, géosciences, lettres, HEC.","Admis en master à l'UNIL. Non-suisse. Résultats excellents.","Français (C1)","2027-03-31","https://www.unil.ch/international/fr/home/menuinst/bourses-et-financements.html"),

// --- Australie ---
B("unimelb.edu.au","University of Melbourne","Bourse Melbourne Graduate 2027","Bourses pour master et doctorat à Melbourne, #1 Australie. 28 000 AUD/an + frais. Tous domaines.","Admis à l'University of Melbourne. Excellence académique.","Anglais (IELTS 6.5+)","2027-04-30","https://scholarships.unimelb.edu.au/"),
B("sydney.edu.au","University of Sydney","Bourse Sydney International 2027","Bourses de 10 000 à 40 000 AUD pour master à l'University of Sydney. Top 20 mondial.","Admis à Sydney. Non-australien.","Anglais (IELTS 6.5+)","2027-04-30","https://www.sydney.edu.au/scholarships.html"),
B("anu.edu.au","Australian National University","Bourse ANU International 2027","Bourses pour master à l'ANU, Canberra. 25 à 50% des frais. Sciences, politique, ingénierie.","Admis à l'ANU. Non-australien.","Anglais (IELTS 6.5+)","2027-04-30","https://www.anu.edu.au/study/scholarships"),
B("uq.edu.au","University of Queensland","Bourse UQ International 2027","Bourses pour master à UQ Brisbane. 10 000 à 20 000 AUD. Ingénierie, sciences, santé.","Admis à UQ. Non-australien.","Anglais (IELTS 6.5+)","2027-04-30","https://scholarships.uq.edu.au/"),

// --- Corée du Sud ---
B("gks.go.kr","NIIED (Gouvernement Coréen)","Bourse GKS Graduate 2027 — Corée du Sud","Programme de bourses du gouvernement coréen (GKS) pour master et doctorat. Frais, allocation, billet d'avion, cours de coréen inclus. Ouvert à 154 pays.","Nationalité d'un pays partenaire. Moins de 40 ans. Licence complétée.","Coréen ou anglais","2027-03-15","https://www.studyinkorea.go.kr/",["recommandation","passeport"]),
B("kaist.ac.kr","KAIST","Bourse KAIST International 2027","Bourses complètes pour master et doctorat au KAIST. Frais + 350 000 KRW/mois. MIT de la Corée. Informatique, IA, robotique.","Admis au KAIST. Non-coréen. Excellence en sciences ou ingénierie.","Anglais","2027-03-31","https://admission.kaist.ac.kr/",["recommandation"]),
B("snu.ac.kr","Seoul National University","Bourse SNU International 2027","Bourses pour master et doctorat à SNU, meilleure université coréenne. Exonération des frais et allocation mensuelle.","Admis à SNU. Non-coréen. Excellence académique.","Anglais ou coréen","2027-03-31","https://en.snu.ac.kr/apply/info",["recommandation"]),
B("yonsei.ac.kr","Yonsei University","Bourse Yonsei Global Leader 2027","Bourses pour master à Yonsei, l'une des 3 meilleures universités de Corée. Underwood International College. Séoul.","Admis à Yonsei. Non-coréen.","Anglais","2027-04-30","https://www.yonsei.ac.kr/en_sc/admission/scholarship.jsp"),

// --- Turquie ---
B("turkiyeburslari.gov.tr","Gouvernement Turc","Bourse Türkiye Burslari 2027","Bourses du gouvernement turc pour licence, master et doctorat. Frais, logement, allocation, billet d'avion, assurance, cours de turc.","Non-turc. Licence pour master, master pour doctorat. Moyenne > 75%.","Turc (cours fournis)","2027-02-20","https://www.turkiyeburslari.gov.tr/",["passeport"]),
B("bilkent.edu.tr","Bilkent University","Bourse Bilkent International 2027","Bourses pour master et doctorat à Bilkent, meilleure université privée de Turquie. Frais + logement + allocation. Ankara.","Admis à Bilkent. Non-turc.","Anglais","2027-06-30","https://w3.bilkent.edu.tr/bilkent/scholarships/"),
B("boun.edu.tr","Bogazici University","Bourse Bogazici Graduate 2027","Bourses pour master à Bogazici, l'une des meilleures universités turques. Istanbul. Ingénierie, sciences, économie.","Admis en master à Bogazici. Non-turc.","Anglais","2027-06-30","https://www.boun.edu.tr/en-US/Content/Admissions/Scholarships"),

// --- Inde ---
B("iccr.gov.in","ICCR (Gouvernement Indien)","Bourse ICCR Afrique 2027 — Inde","Bourses du Conseil Indien des Relations Culturelles pour étudiants africains. Licence, master, doctorat dans les universités indiennes. Frais + allocation.","Nationalité africaine. Diplôme requis pour le niveau visé.","Anglais","2027-03-31","https://www.iccr.gov.in/scholarship",["passeport"]),
B("iitd.ac.in","IIT Delhi","Bourse IIT Delhi International 2027","Bourses pour master et doctorat à IIT Delhi, meilleur institut technologique d'Inde. Informatique, IA, mécanique, électrique.","Admis à IIT Delhi. Non-indien. Excellence en sciences/ingénierie.","Anglais","2027-04-30","https://home.iitd.ac.in/admissions.php",["recommandation"]),

// --- Russie ---
B("russia.study","Gouvernement Russe","Bourse Gouvernement Russe 2027","Bourses du gouvernement russe pour étudiants étrangers. 30 000+ places. Frais, logement, allocation. Toutes disciplines dans les universités russes.","Non-russe. Diplôme requis pour le niveau. 18-35 ans.","Russe (cours préparatoire fourni)","2027-03-31","https://education-in-russia.com/",["passeport"]),
B("msu.ru","Moscow State University","Bourse MSU International 2027","Bourses pour master à l'Université d'État de Moscou, la plus prestigieuse de Russie. Sciences, mathématiques, physique, chimie.","Admis à MSU. Non-russe.","Russe ou anglais","2027-05-31","https://www.msu.ru/en/admissions/"),

// --- Chine supplémentaire ---
B("csc.edu.cn","China Scholarship Council","Bourse CSC Bilateral 2027 — Bénin","Bourses bilatérales CSC pour étudiants béninois. Master et doctorat dans les universités chinoises. Frais, logement, allocation, billet.","Nationalité béninoise. Licence pour master, master pour doctorat. Moins de 35 ans (master) ou 40 ans (doctorat).","Chinois ou anglais","2027-03-31","https://www.csc.edu.cn/",["passeport","recommandation"]),
B("sjtu.edu.cn","Shanghai Jiao Tong University","Bourse SJTU International 2027","Bourses pour master et doctorat à SJTU, top 5 Chine. Ingénierie, informatique, management, médecine. Programmes en anglais.","Admis à SJTU. Non-chinois. Moins de 35 ans pour master.","Anglais ou chinois","2027-03-31","https://www.sjtu.edu.cn/scholarship/",["recommandation"]),
B("whu.edu.cn","Wuhan University","Bourse Wuhan University 2027","Bourses pour master et doctorat à Wuhan University. Informatique, télécoms, droit, médecine. Programmes en anglais disponibles.","Admis à Wuhan University. Non-chinois.","Anglais ou chinois","2027-04-30","https://www.whu.edu.cn/"),
B("hust.edu.cn","HUST","Bourse HUST International 2027","Bourses pour master à l'Université des Sciences et Technologies de Huazhong. Ingénierie, sciences, médecine. Wuhan.","Admis à HUST. Non-chinois.","Anglais ou chinois","2027-04-30","https://www.hust.edu.cn/"),
B("xjtu.edu.cn","Xi'an Jiaotong University","Bourse XJTU Silk Road 2027","Bourses Silk Road pour master et doctorat à XJTU. Énergie, informatique, management. Route de la Soie académique.","Admis à XJTU. Non-chinois. Pays de la Route de la Soie (inclut Afrique).","Anglais ou chinois","2027-04-30","https://www.xjtu.edu.cn/"),

// --- Bourses internationales programmes ---
B("twas.org","TWAS","Bourse TWAS-CNPq Brésil 2027","Bourses TWAS pour chercheurs de pays en développement pour doctorat au Brésil. Allocation brésilienne + billet d'avion.","Doctorant de pays en développement. Moins de 35 ans. Accepté dans une université brésilienne.","Anglais ou portugais","2027-09-30","https://twas.org/opportunities/fellowships",["projet","recommandation"]),
B("aaas.org","AAAS","Bourse AAAS Science Diplomacy 2027","Bourses en diplomatie scientifique de l'AAAS. Placement dans des agences gouvernementales américaines. Pour chercheurs de tous pays.","Doctorat en sciences, ingénierie ou santé. Expérience de recherche.","Anglais courant","2027-11-01","https://www.aaas.org/programs/science-technology-policy-fellowships",["projet"]),
B("aims.ac.za","AIMS","Bourse AIMS Master 2027 — Mathématiques Afrique","Bourses pour master en sciences mathématiques dans les centres AIMS en Afrique (Afrique du Sud, Rwanda, Ghana, Cameroun, Sénégal). Frais complets.","Licence en mathématiques, physique ou ingénierie. Nationalité africaine.","Anglais ou français","2027-03-31","https://www.aims.ac.za/",["recommandation"]),

// --- Bourses Moyen-Orient ---
B("kaust.edu.sa","KAUST","Bourse KAUST Fellowship 2027 — Arabie Saoudite","Bourses complètes pour master et doctorat à KAUST. Frais, logement, allocation 20 000-30 000 USD/an. Sciences, ingénierie, informatique.","Licence en sciences ou ingénierie. Tout pays.","Anglais","2027-01-15","https://www.kaust.edu.sa/en/study/applying-to-kaust",["recommandation"]),
B("nyuad.nyu.edu","NYU Abu Dhabi","Bourse NYU Abu Dhabi Graduate 2027","Bourses pour master à NYU Abu Dhabi. Frais complets + allocation. Campus international aux Émirats.","Admis en master à NYUAD. Tout pays. Excellence académique.","Anglais","2027-01-15","https://nyuad.nyu.edu/en/admissions/graduate.html"),
B("education.gov.il","Gouvernement Israélien","Bourse Israël Développement 2027","Bourses du gouvernement israélien pour étudiants de pays en développement. Master et recherche dans les universités israéliennes. 8 mois.","Nationalité d'un pays en développement. Licence minimum. Moins de 35 ans.","Anglais ou hébreu","2027-11-30","https://www.scholarship.gov.il/",["passeport"]),

// --- Amérique latine ---
B("itesm.mx","Tec de Monterrey","Bourse Tec de Monterrey Leadership 2027","Bourses pour master au Tec de Monterrey, meilleure université privée du Mexique. Business, ingénierie, IA. Campus principal à Monterrey.","Admis en master au Tec. Tout pays.","Espagnol ou anglais","2027-05-31","https://tec.mx/en/admissions/scholarships"),
B("usp.br","Universidade de São Paulo","Bourse USP International 2027 — Brésil","Bourses pour master et doctorat à l'USP, meilleure université d'Amérique latine. Sciences, médecine, ingénierie, lettres. São Paulo.","Admis à l'USP. Non-brésilien.","Portugais ou anglais","2027-06-30","https://www.usp.br/"),

// --- France supplémentaire ---
B("ens-lyon.fr","ENS Lyon","Bourse ENS Lyon International 2027","Bourses pour master à l'ENS Lyon. Sciences, lettres, informatique. Formation d'excellence de type normalien. 1 000 EUR/mois.","Admis à l'ENS Lyon. Non-européen. Excellence académique exceptionnelle.","Français (C1)","2027-01-15","https://www.ens-lyon.fr/formation/bourses-aides",["recommandation"]),
B("ensae.fr","ENSAE Paris","Bourse ENSAE International 2027","Bourses pour le cycle ingénieur et master à l'ENSAE Paris. Statistique, data science, économie quantitative, finance.","Admis à l'ENSAE. Excellent niveau en mathématiques.","Français ou anglais","2027-04-30","https://www.ensae.fr/admission/bourses/",["recommandation"]),
B("telecom-paris.fr","Télécom Paris","Bourse Télécom Paris International 2027","Bourses pour cycle ingénieur et master à Télécom Paris (Institut Polytechnique de Paris). IA, cybersécurité, data science, réseaux.","Admis à Télécom Paris. Excellence en sciences.","Français ou anglais","2027-04-30","https://www.telecom-paris.fr/fr/formation/financer-ses-etudes",["recommandation"]),
B("agroparistech.fr","AgroParisTech","Bourse AgroParisTech International 2027","Bourses pour ingénieurs et master à AgroParisTech. Agronomie, alimentation, environnement, forêt. Paris et campus régionaux.","Admis à AgroParisTech. Non-européen.","Français (B2+)","2027-04-30","https://www.agroparistech.fr/international/bourses",["recommandation"]),

// ══════════════════════════════════════════════
// BLOC 2 — EMPLOI SUPPLÉMENTAIRES (180 entrées)
// ══════════════════════════════════════════════

// --- Grandes entreprises tech internationales ---
E("google.com","Google","Google — Software Engineer Afrique 2027","Poste d'ingénieur logiciel chez Google pour le bureau d'Accra (Ghana), hub tech de Google en Afrique. Backend, Android, Cloud, IA.","Master en informatique. Compétences en algorithmes, structures de données. Expérience en Python, Java ou C++.","Anglais courant","2027-06-30","https://careers.google.com/"),
E("microsoft.com","Microsoft","Microsoft — Cloud Solutions Architect Afrique 2027","Poste d'architecte solutions cloud chez Microsoft pour l'Afrique. Azure, Office 365, Dynamics 365. Basé à Lagos, Nairobi ou Le Caire.","Master en informatique ou ingénierie. Certifications Azure appréciées.","Anglais courant","2027-06-30","https://careers.microsoft.com/"),
E("meta.com","Meta","Meta — Data Scientist 2027","Poste de data scientist chez Meta (Facebook, Instagram, WhatsApp). Analyse de données à grande échelle, apprentissage automatique, expérimentation.","Master ou doctorat en statistique, informatique ou mathématiques. Compétences en Python et SQL.","Anglais courant","2027-06-30","https://www.metacareers.com/"),
E("apple.com","Apple","Apple — Hardware Engineer 2027","Poste d'ingénieur matériel chez Apple. Conception de puces, circuits intégrés, systèmes embarqués. Cupertino ou London.","Master en ingénierie électrique ou informatique. Expérience ASIC/FPGA.","Anglais courant","2027-06-30","https://jobs.apple.com/"),
E("amazon.jobs","Amazon","Amazon — Operations Manager 2027","Poste de responsable opérations chez Amazon. Gestion de centre de distribution, optimisation logistique, leadership d'équipe.","Master en logistique, supply chain ou ingénierie industrielle.","Anglais courant","2027-06-30","https://www.amazon.jobs/"),
E("salesforce.com","Salesforce","Salesforce — Solution Engineer 2027","Poste d'ingénieur solutions chez Salesforce. Démonstrations CRM, architecture de solutions cloud, accompagnement clients.","Master en informatique ou commerce. Connaissance du CRM.","Anglais courant","2027-06-30","https://www.salesforce.com/company/careers/"),
E("oracle.com","Oracle","Oracle — Cloud Engineer Afrique 2027","Poste d'ingénieur cloud chez Oracle pour la région Afrique. Oracle Cloud Infrastructure, bases de données, ERP Cloud.","Master en informatique. Expérience cloud et bases de données.","Anglais et/ou français","2027-06-30","https://www.oracle.com/careers/"),
E("ibm.com","IBM","IBM — AI Consultant 2027","Poste de consultant en IA chez IBM. Déploiement de Watson, automatisation, cloud hybride. Projets en Afrique et Europe.","Master en informatique, IA ou data science.","Anglais et/ou français","2027-06-30","https://www.ibm.com/careers"),
E("nvidia.com","NVIDIA","NVIDIA — Deep Learning Engineer 2027","Poste d'ingénieur deep learning chez NVIDIA. GPU computing, LLM, vision par ordinateur, robotique autonome.","Master ou doctorat en IA, informatique. Compétences CUDA, PyTorch.","Anglais courant","2027-06-30","https://www.nvidia.com/en-us/about-nvidia/careers/"),
E("intel.com","Intel","Intel — Process Engineer 2027","Poste d'ingénieur procédé chez Intel. Fabrication de semi-conducteurs, lithographie, métrologie. Usines en Irlande, Israël, USA.","Master en physique, chimie, ou ingénierie des matériaux.","Anglais courant","2027-06-30","https://jobs.intel.com/"),

// --- Banques internationales ---
E("jpmorgan.com","JPMorgan Chase","JPMorgan — Analyst Programme 2027","Programme analyst chez JPMorgan Chase, plus grande banque mondiale. Investment banking, markets, asset management, technology.","Master en finance, économie, mathématiques ou informatique.","Anglais courant","2027-01-31","https://careers.jpmorgan.com/",["diplome"]),
E("goldmansachs.com","Goldman Sachs","Goldman Sachs — Analyst 2027","Programme analyst chez Goldman Sachs. Investment banking, trading, asset management, ingénierie. New York, London, Hong Kong.","Master en finance, économie, mathématiques ou informatique.","Anglais courant","2027-01-31","https://www.goldmansachs.com/careers/",["diplome"]),
E("ubs.com","UBS","UBS — Graduate Programme 2027","Programme diplômé chez UBS, plus grande banque suisse. Wealth management, investment banking, asset management. Zurich, London, NY.","Master en finance, économie ou mathématiques.","Anglais courant, allemand apprécié","2027-03-31","https://www.ubs.com/global/en/careers.html"),
E("credit-suisse.com","Credit Suisse","Credit Suisse/UBS — Analyst Programme 2027","Programme analyst chez Credit Suisse (désormais UBS). Wealth management, banque d'investissement. Zurich, London.","Master en finance ou économie.","Anglais courant","2027-03-31","https://www.ubs.com/global/en/careers.html"),
E("hsbc.com","HSBC","HSBC — Graduate Programme 2027","Programme diplômé chez HSBC, banque mondiale. Commercial banking, Global Banking, Wealth. Présence en Afrique (Ghana, Maurice).","Master en finance, économie ou commerce.","Anglais courant, français apprécié","2027-03-31","https://www.hsbc.com/careers",["diplome"]),

// --- Consulting ---
E("mckinsey.com","McKinsey","McKinsey — Business Analyst Afrique 2027","Poste de business analyst chez McKinsey & Company pour le bureau d'Afrique (Lagos, Johannesburg, Casablanca). Conseil en stratégie.","Master d'une grande école ou université. Excellence académique. Leadership.","Anglais courant, français apprécié","2027-04-30","https://www.mckinsey.com/careers",["diplome"]),
E("bcg.com","Boston Consulting Group","BCG — Consultant Junior Afrique 2027","Poste de consultant junior chez BCG pour l'Afrique (Casablanca, Lagos). Stratégie, digital, transformation.","Master d'une grande école. Résultats académiques top.","Anglais et français","2027-04-30","https://careers.bcg.com/"),
E("bain.com","Bain & Company","Bain — Associate Consultant 2027","Poste de consultant associé chez Bain & Company. Bureau de Johannesburg ou Dubaï couvrant l'Afrique.","Master d'une grande école ou université. Excellence académique et leadership.","Anglais courant","2027-04-30","https://www.bain.com/careers/"),
E("rolandberger.com","Roland Berger","Roland Berger — Consultant Junior 2027","Poste de consultant junior chez Roland Berger, cabinet stratégique européen. Bureaux au Maroc et en Afrique de l'Ouest.","Master d'une grande école de commerce ou d'ingénieurs.","Français et anglais","2027-06-30","https://www.rolandberger.com/en/Careers.html"),
E("kearney.com","Kearney","Kearney — Business Analyst EMEA 2027","Poste de business analyst chez Kearney (anciennement AT Kearney). Conseil en opérations et stratégie. Couverture Moyen-Orient et Afrique.","Master en ingénierie, commerce ou économie.","Anglais courant","2027-06-30","https://www.kearney.com/careers"),

// --- Pharmaceutique ---
E("novartis.com","Novartis","Novartis — Clinical Research Associate 2027","Poste d'associé de recherche clinique chez Novartis. Essais cliniques, oncologie, immunologie. Afrique et Europe.","Doctorat en pharmacie, médecine ou biologie. Expérience en essais cliniques.","Anglais courant, français apprécié","2027-06-30","https://www.novartis.com/careers"),
E("roche.com","Roche","Roche — Data Scientist Pharma 2027","Poste de data scientist chez Roche, leader mondial en diagnostics. Analyse de données cliniques, IA pour la santé.","Master ou doctorat en biostatistique, informatique ou bioinformatique.","Anglais courant","2027-06-30","https://careers.roche.com/"),
E("gsk.com","GSK","GSK — Regulatory Affairs 2027","Poste en affaires réglementaires chez GSK. Dossiers d'AMM, pharmacovigilance. Couverture Afrique depuis London ou Nairobi.","Doctorat en pharmacie ou sciences. Connaissance de la réglementation pharmaceutique.","Anglais courant","2027-06-30","https://www.gsk.com/en-gb/careers/"),
E("merck.com","Merck","Merck — Process Development Scientist 2027","Poste de scientifique en développement de procédé chez Merck. Bioproduction, procédés chimiques, scale-up. Darmstadt ou Boston.","Doctorat en chimie, biochimie ou ingénierie chimique.","Anglais courant","2027-06-30","https://www.merckgroup.com/en/careers.html"),
E("astrazeneca.com","AstraZeneca","AstraZeneca — Medical Advisor Afrique 2027","Poste de conseiller médical chez AstraZeneca pour l'Afrique. Oncologie, respiratoire, cardiovasculaire. Relations avec les KOLs.","Doctorat en médecine ou pharmacie. Expérience en affaires médicales.","Anglais courant, français apprécié","2027-06-30","https://careers.astrazeneca.com/"),

// --- Agroalimentaire ---
E("nestle.com","Nestlé","Nestlé — Management Trainee Afrique 2027","Programme Management Trainee chez Nestlé pour l'Afrique. Marketing, supply chain, finance, technique. Usines en CI, Ghana, Nigeria, Cameroun.","Master en commerce, ingénierie, supply chain ou marketing.","Français et/ou anglais","2027-04-30","https://www.nestle.com/jobs"),
E("danone.com","Danone","Danone — Graduate Programme 2027","Programme diplômé chez Danone. Produits laitiers, eaux, nutrition. Opérations en Afrique (Maroc, Égypte, Afrique du Sud).","Master en agroalimentaire, commerce ou ingénierie.","Français et/ou anglais","2027-05-31","https://careers.danone.com/"),
E("cargill.com","Cargill","Cargill — Supply Chain Trainee 2027","Programme trainee supply chain chez Cargill, géant de l'agroalimentaire. Cacao, grains, huiles. Opérations en CI, Ghana, Cameroun.","Master en supply chain, agro-économie ou ingénierie.","Anglais et/ou français","2027-06-30","https://careers.cargill.com/"),
E("olam.com","Olam","Olam — Trading Analyst Afrique 2027","Poste d'analyste trading chez Olam (rebaptisé ofi), leader du négoce agricole en Afrique. Cacao, café, noix de cajou, coton.","Master en finance, économie agricole ou commerce international.","Anglais courant","2027-06-30","https://www.olamgroup.com/careers.html"),
E("mars.com","Mars","Mars — Associate Manager Afrique 2027","Poste de manager associé chez Mars (M&Ms, Pedigree, Uncle Ben's). Usines en CI (cacao), Kenya. Supply chain, marketing.","Master en commerce, marketing ou supply chain.","Anglais et/ou français","2027-06-30","https://careers.mars.com/"),

// --- Automobiles allemandes supplémentaires ---
E("mercedes-benz.com","Mercedes-Benz","Mercedes-Benz — Design Engineer 2027","Poste d'ingénieur design chez Mercedes-Benz. Conception véhicules, matériaux, aérodynamique. Stuttgart et Sindelfingen.","Master en ingénierie mécanique ou design industriel.","Anglais courant, allemand apprécié","2027-06-30","https://www.mercedes-benz.com/en/career/"),
E("audi.com","Audi","Audi — Production Planning Engineer 2027","Poste d'ingénieur planification production chez Audi. Usine d'Ingolstadt et Neckarsulm. Industrie 4.0, lean manufacturing.","Master en ingénierie industrielle ou mécanique.","Anglais et allemand","2027-06-30","https://www.audi.com/en/career.html"),
E("porsche.com","Porsche","Porsche — Software Developer 2027","Poste de développeur logiciel chez Porsche. Systèmes embarqués, électromobilité, digital services. Stuttgart.","Master en informatique, ingénierie logicielle ou électronique.","Anglais courant, allemand apprécié","2027-06-30","https://www.porsche.com/careers/"),
E("continental.com","Continental","Continental — R&D Engineer 2027","Poste d'ingénieur R&D chez Continental. Pneus, freinage, capteurs, conduite autonome. Hanover et sites mondiaux.","Master en ingénierie mécanique, matériaux ou électronique.","Anglais courant","2027-06-30","https://www.continental.com/en/career/"),
E("zf.com","ZF Friedrichshafen","ZF — Powertrain Engineer 2027","Poste d'ingénieur powertrain chez ZF, leader mondial des transmissions. Électrification, hybride, châssis. Friedrichshafen.","Master en ingénierie mécanique ou électrique.","Anglais et allemand","2027-06-30","https://www.zf.com/careers/"),

// --- Énergie & Environnement ---
E("edf.fr","EDF","EDF — Ingénieur Énergie Afrique 2027","Poste d'ingénieur chez EDF Renewables en Afrique. Solaire, éolien, hydroélectrique. Projets en Afrique de l'Ouest et du Nord.","Master en énergie, génie électrique ou environnement.","Français courant, anglais apprécié","2027-06-30","https://www.edf.fr/groupe-edf/rejoignez-nous"),
E("engie.com","Engie","Engie — Chef de Projet Solaire Afrique 2027","Poste de chef de projet solaire chez Engie Africa. Centrales solaires, mini-grids, accès à l'énergie. Sénégal, CI, Cameroun.","Master en énergie renouvelable, génie électrique ou environnement.","Français et anglais","2027-06-30","https://www.engie.com/talents/nos-offres"),
E("schneider-electric.com","Schneider Electric","Schneider Electric — Graduate Programme 2027","Programme diplômé chez Schneider Electric. Gestion de l'énergie, automatisation, IoT. Présence en Afrique de l'Ouest.","Master en génie électrique, énergie ou automatisme.","Français et/ou anglais","2027-06-30","https://www.se.com/ww/en/about-us/careers/"),
E("shell.com","Shell","Shell — Graduate Engineer 2027","Programme diplômé chez Shell. Pétrole, gaz, énergies nouvelles. Opérations au Nigeria, Gabon, Afrique du Sud.","Master en ingénierie pétrolière, chimique, mécanique ou géosciences.","Anglais courant","2027-04-30","https://www.shell.com/careers"),
E("bp.com","BP","BP — Engineering Graduate 2027","Programme diplômé ingénieur chez BP. Transition énergétique, gaz, renouvelables. Opérations en Afrique (Angola, Égypte, Mauritanie).","Master en ingénierie chimique, mécanique ou pétrolière.","Anglais courant","2027-04-30","https://www.bp.com/en/global/corporate/careers.html"),

// --- Luxe ---
E("hermes.com","Hermès","Hermès — Artisan Maroquinier 2027","Poste d'artisan maroquinier chez Hermès. Fabrication de sacs et accessoires de luxe. Ateliers en France (Pantin, Normandie).","CAP/BEP en maroquinerie ou expérience artisanale. Précision et minutie.","Français courant","2027-06-30","https://www.hermes.com/fr/fr/story/carrieres/"),
E("chanel.com","Chanel","Chanel — Marketing Manager 2027","Poste de responsable marketing chez Chanel. Stratégie digitale, campagnes produit, retail marketing. Paris.","Master en marketing, commerce ou luxe. 3+ ans d'expérience.","Français et anglais","2027-06-30","https://careers.chanel.com/"),
E("kering.com","Kering","Kering — Sustainability Manager 2027","Poste de responsable développement durable chez Kering (Gucci, YSL, Bottega Veneta). Stratégie environnementale, reporting ESG.","Master en environnement, RSE ou développement durable. Expérience luxe/mode.","Français et anglais","2027-06-30","https://www.kering.com/en/talent/"),

// --- ONG et organisations internationales ---
E("msf.org","Médecins Sans Frontières","MSF — Coordinateur Terrain Afrique 2027","Poste de coordinateur terrain chez MSF en Afrique. Gestion de mission, coordination médicale, logistique humanitaire. RDC, Niger, Nigeria, Mali.","Master en médecine, santé publique, logistique ou gestion. Expérience humanitaire.","Français et anglais","2027-06-30","https://www.msf.org/work-msf"),
E("icrc.org","CICR","CICR — Délégué Afrique 2027","Poste de délégué du CICR en Afrique. Protection, droit international humanitaire, visites aux détenus. Terrain en zones de conflit.","Master en droit, relations internationales ou sciences politiques. 2+ ans d'expérience.","Français et anglais","2027-06-30","https://www.icrc.org/en/jobs"),
E("unhcr.org","UNHCR","UNHCR — Associate Protection Officer 2027","Poste d'officier de protection associé au HCR. Assistance aux réfugiés, asile, solutions durables. Afrique de l'Ouest et Sahel.","Master en droit, relations internationales ou droits humains.","Français et anglais","2027-06-30","https://www.unhcr.org/careers.html"),
E("unicef.org","UNICEF","UNICEF — Spécialiste Éducation Bénin 2027","Poste de spécialiste éducation chez UNICEF Bénin. Accès à l'éducation, qualité, équité. Bureau de Cotonou.","Master en éducation, sciences sociales ou développement.","Français courant, anglais apprécié","2027-06-30","https://www.unicef.org/careers"),
E("wfp.org","PAM","PAM — Logistics Officer Afrique 2027","Poste de logisticien au Programme Alimentaire Mondial en Afrique. Supply chain humanitaire, gestion d'entrepôts, transport.","Master en logistique, supply chain ou gestion. Expérience terrain.","Français et anglais","2027-06-30","https://www.wfp.org/careers"),
E("who.int","OMS","OMS — Epidemiologist Afrique 2027","Poste d'épidémiologiste à l'OMS en Afrique. Surveillance, riposte aux épidémies, vaccination. Bureau régional de Brazzaville.","Doctorat ou master en épidémiologie, santé publique ou biostatistique.","Français et anglais","2027-06-30","https://www.who.int/careers"),
E("fao.org","FAO","FAO — Agronome Afrique de l'Ouest 2027","Poste d'agronome à la FAO en Afrique de l'Ouest. Sécurité alimentaire, résilience, systèmes agricoles durables.","Master en agronomie, économie agricole ou développement rural.","Français courant, anglais apprécié","2027-06-30","https://jobs.fao.org/"),
E("undp.org","PNUD","PNUD — Programme Analyst Bénin 2027","Poste d'analyste de programme chez le PNUD au Bénin. Gouvernance, changement climatique, développement humain.","Master en économie, relations internationales ou développement.","Français courant, anglais apprécié","2027-06-30","https://jobs.undp.org/"),

// --- Entreprises japonaises ---
E("toyota.com","Toyota","Toyota — Production Engineer 2027","Poste d'ingénieur de production chez Toyota. Système de production Toyota (TPS), lean manufacturing. Toyota City et usines mondiales.","Master en ingénierie industrielle, mécanique ou qualité.","Anglais ou japonais","2027-06-30","https://global.toyota/en/careers/"),
E("sony.com","Sony","Sony — AI Research Engineer 2027","Poste d'ingénieur recherche en IA chez Sony. Vision par ordinateur, NLP, robotique, audio AI. Tokyo et Paris.","Master ou doctorat en IA, informatique ou mathématiques.","Anglais courant","2027-06-30","https://www.sony.com/en/SonyInfo/Careers/"),
E("panasonic.com","Panasonic","Panasonic — Battery Engineer 2027","Poste d'ingénieur batteries chez Panasonic. Batteries lithium-ion, véhicules électriques, stockage d'énergie. Osaka.","Master en chimie, matériaux ou ingénierie électrique.","Anglais ou japonais","2027-06-30","https://holdings.panasonic/global/corporate/careers/"),
E("mitsubishi.com","Mitsubishi Corporation","Mitsubishi — Business Development Afrique 2027","Poste de développement commercial chez Mitsubishi Corporation pour l'Afrique. Commerce, énergie, infrastructure, agro. Tokyo et Afrique.","Master en commerce international, économie ou ingénierie.","Anglais courant, japonais apprécié","2027-06-30","https://www.mitsubishicorp.com/jp/en/career/"),
E("hitachi.com","Hitachi","Hitachi — Digital Solutions Engineer 2027","Poste d'ingénieur solutions digitales chez Hitachi. IoT, smart cities, infrastructure ferroviaire, énergie. Lumada platform.","Master en informatique, ingénierie ou data science.","Anglais courant","2027-06-30","https://www.hitachi.com/careers/"),

// --- Entreprises coréennes ---
E("samsung.com","Samsung","Samsung — Semiconductor Engineer 2027","Poste d'ingénieur semi-conducteurs chez Samsung. Mémoire DRAM/NAND, processeurs, fonderie. Pyeongtaek et Austin.","Master en micro-électronique, physique ou matériaux.","Anglais ou coréen","2027-06-30","https://www.samsung.com/global/careers/"),
E("lge.com","LG Electronics","LG — Product Manager 2027","Poste de chef de produit chez LG Electronics. TV OLED, électroménager, solutions B2B. Séoul et marchés africains.","Master en marketing, commerce ou ingénierie.","Anglais courant","2027-06-30","https://www.lg.com/global/careers"),
E("hyundai.com","Hyundai","Hyundai — EV Platform Engineer 2027","Poste d'ingénieur plateforme véhicules électriques chez Hyundai. E-GMP, batteries, moteurs électriques. Ulsan, Corée.","Master en ingénierie automobile, électrique ou mécanique.","Anglais ou coréen","2027-06-30","https://www.hyundai.com/worldwide/en/company/careers"),

// --- Entreprises indiennes ---
E("tcs.com","TCS","TCS — IT Consultant 2027","Poste de consultant IT chez Tata Consultancy Services, plus grande SSII indienne. Digital, cloud, IA. Présence en Afrique.","Master en informatique. Compétences en Java, Python ou cloud.","Anglais courant","2027-06-30","https://www.tcs.com/careers"),
E("infosys.com","Infosys","Infosys — Systems Engineer 2027","Poste d'ingénieur systèmes chez Infosys. Développement, maintenance, cloud, IA. Bangalore et sites mondiaux.","Licence ou master en informatique.","Anglais courant","2027-06-30","https://www.infosys.com/careers/"),
E("wipro.com","Wipro","Wipro — Cloud Engineer 2027","Poste d'ingénieur cloud chez Wipro. Migration cloud, DevOps, sécurité. Bangalore et Afrique.","Master en informatique. Certifications AWS/Azure appréciées.","Anglais courant","2027-06-30","https://careers.wipro.com/"),

// --- Télécoms internationales ---
E("ericsson.com","Ericsson","Ericsson — 5G Network Engineer 2027","Poste d'ingénieur réseau 5G chez Ericsson. Déploiement 5G, RAN, cœur de réseau. Afrique et Moyen-Orient.","Master en télécommunications ou ingénierie réseau.","Anglais courant","2027-06-30","https://www.ericsson.com/en/careers"),
E("nokia.com","Nokia","Nokia — Software Developer 2027","Poste de développeur logiciel chez Nokia. Solutions réseau, OSS/BSS, cloud natif. Helsinki et sites africains.","Master en informatique ou télécommunications.","Anglais courant","2027-06-30","https://www.nokia.com/careers/"),

// --- Ciment et matériaux ---
E("lafargeholcim.com","Holcim","Holcim — Process Engineer Afrique 2027","Poste d'ingénieur procédé chez Holcim (ex-LafargeHolcim) en Afrique. Cimenteries au Nigeria, Cameroun, CI, Tanzanie. Process, maintenance, HSE.","Master en génie chimique, mécanique ou matériaux.","Français et/ou anglais","2027-06-30","https://www.holcim.com/careers"),
E("dangote.com","Dangote Group","Dangote — Postes Industrie Nigeria 2027","Postes chez Dangote, plus grand conglomérat d'Afrique de l'Ouest. Ciment, sucre, sel, raffinerie. Nigeria et expansion régionale.","Diplôme en ingénierie, chimie, commerce ou finance.","Anglais courant","2027-06-30","https://www.dangote.com/careers/"),
E("heidelbergcement.com","Heidelberg Materials","Heidelberg Materials — Graduate Afrique 2027","Programme diplômé chez Heidelberg Materials en Afrique. Ciment, béton, granulats. Togo, Ghana, Tanzania, Bénin.","Master en génie civil, chimique ou mécanique.","Anglais et/ou français","2027-06-30","https://www.heidelbergmaterials.com/en/careers"),

// --- Aviation ---
E("airbus.com","Airbus","Airbus — Systems Engineer 2027","Poste d'ingénieur systèmes chez Airbus. Avionique, systèmes de vol, certification. Toulouse et Hambourg.","Master en aéronautique, ingénierie des systèmes ou automatisme.","Anglais courant, français apprécié","2027-06-30","https://www.airbus.com/en/careers"),
E("safrangroup.com","Safran","Safran — Ingénieur Moteur 2027","Poste d'ingénieur chez Safran. Moteurs d'avion (LEAP), trains d'atterrissage, nacelles. Île-de-France et Bordeaux.","Master en aéronautique, mécanique ou thermique.","Français courant, anglais apprécié","2027-06-30","https://www.safran-group.com/fr/emplois"),
E("rolls-royce.com","Rolls-Royce","Rolls-Royce — Graduate Engineering 2027","Programme diplômé ingénieur chez Rolls-Royce. Moteurs d'avion, systèmes navals, énergie nucléaire. Derby et Bristol.","Master en aéronautique, mécanique ou matériaux.","Anglais courant","2027-06-30","https://careers.rolls-royce.com/"),

// ══════════════════════════════════════════════
// BLOC 3 — ADMISSIONS SUPPLÉMENTAIRES (60)
// ══════════════════════════════════════════════

A("mit.edu","MIT","Admission MIT Graduate 2027","Candidature en master et doctorat au MIT. Informatique, ingénierie, économie, architecture, science des matériaux. Cambridge, Massachusetts.","Licence avec excellence. GRE recommandé. Lettres de recommandation.","Anglais (TOEFL 100+)","2027-01-05","https://gradadmissions.mit.edu/",["recommandation"]),
A("stanford.edu","Stanford University","Admission Stanford Graduate 2027","Candidature en master et doctorat à Stanford. Informatique, ingénierie, business, médecine, droit. Silicon Valley.","Licence avec excellence. GRE selon le programme. Lettres de recommandation.","Anglais (TOEFL 100+)","2027-01-10","https://gradadmissions.stanford.edu/",["recommandation"]),
A("harvard.edu","Harvard University","Admission Harvard Graduate School 2027","Candidature en master à Harvard. Kennedy School, GSAS, School of Education, School of Public Health.","Licence avec excellence. GRE souvent requis. Statement of purpose.","Anglais (TOEFL 100+)","2027-01-05","https://gsas.harvard.edu/admissions",["recommandation"]),
A("ox.ac.uk","University of Oxford","Admission Oxford Graduate 2027","Candidature en master et doctorat à Oxford. Sciences, lettres, droit, médecine, ingénierie. Plus ancienne université anglophone.","Licence mention très bien ou équivalent. Lettres de recommandation.","Anglais (IELTS 7.5+)","2027-01-20","https://www.ox.ac.uk/admissions/graduate/",["recommandation"]),
A("cam.ac.uk","University of Cambridge","Admission Cambridge Graduate 2027","Candidature en master et doctorat à Cambridge. Sciences, ingénierie, lettres, droit, économie.","Licence mention très bien ou équivalent. First class honours.","Anglais (IELTS 7.5+)","2027-01-10","https://www.graduate.study.cam.ac.uk/",["recommandation"]),
A("caltech.edu","Caltech","Admission Caltech Graduate 2027","Candidature en master et doctorat à Caltech. Sciences fondamentales, ingénierie, informatique. Pasadena.","Licence en sciences avec excellence. GRE recommandé.","Anglais (TOEFL 100+)","2027-01-05","https://www.gradoffice.caltech.edu/admissions",["recommandation"]),
A("ethz.ch","ETH Zurich","Admission ETH Zurich Master 2027","Candidature en master à ETH Zurich. Informatique, physique, ingénierie, architecture. Meilleure université d'Europe continentale.","Licence en sciences ou ingénierie avec excellence. Test GRE recommandé.","Anglais","2027-12-15","https://ethz.ch/en/studies/master.html",["recommandation"]),
A("ntu.edu.sg","NTU Singapore","Admission NTU Master 2027","Candidature en master à NTU (Nanyang Technological University). Ingénierie, informatique, business, sciences. Singapour.","Licence avec bons résultats. GRE/GMAT selon le programme.","Anglais","2027-01-31","https://www.ntu.edu.sg/admissions/graduate",["recommandation"]),
A("nus.edu.sg","NUS Singapore","Admission NUS Master 2027","Candidature en master à NUS (National University of Singapore). Top 10 mondial. Tous domaines.","Licence avec bons résultats.","Anglais","2027-01-15","https://www.nus.edu.sg/registrar/academic-information-policies/graduate",["recommandation"]),
A("hku.hk","University of Hong Kong","Admission HKU Master 2027","Candidature en master à HKU. Business, droit, ingénierie, sciences sociales. Hong Kong.","Licence avec bons résultats. Test IELTS/TOEFL requis.","Anglais (IELTS 6.5+)","2027-04-30","https://www.gradsch.hku.hk/gradsch/prospective-students/how-to-apply"),

A("uclouvain.be","UCLouvain","Admission UCLouvain Master 2027","Candidature en master à l'UCLouvain. Ingénierie, sciences, droit, économie, lettres. Plus ancienne université de Belgique.","Licence ou équivalent. Dossier académique.","Français","2027-04-30","https://uclouvain.be/en/study/inscriptions"),
A("ulb.be","ULB","Admission ULB Master 2027","Candidature en master à l'Université Libre de Bruxelles. Sciences, ingénierie, droit, politique. Bruxelles.","Licence ou équivalent. Dossier académique.","Français","2027-04-30","https://www.ulb.be/en/apply"),
A("uliege.be","ULiège","Admission ULiège Master 2027","Candidature en master à l'Université de Liège. Sciences, ingénierie, médecine, droit. Belgique francophone.","Licence ou équivalent.","Français","2027-04-30","https://www.uliege.be/cms/c_9093595/en/admission"),
A("uni.lu","Université du Luxembourg","Admission Luxembourg Master 2027","Candidature en master à l'Université du Luxembourg. Finance, droit européen, informatique, ingénierie. Cadre multilingue.","Licence ou équivalent.","Français, anglais ou allemand","2027-04-30","https://wwwfr.uni.lu/studies/admission"),
A("uottawa.ca","Université d'Ottawa","Admission Ottawa Master 2027","Candidature en master à l'Université d'Ottawa. Bilingue français-anglais. Droit, santé, ingénierie, sciences sociales.","Licence avec bonne moyenne.","Français ou anglais","2027-03-01","https://www.uottawa.ca/graduate-studies/programs"),
A("usherbrooke.ca","Université de Sherbrooke","Admission Sherbrooke Master 2027","Candidature en master à l'Université de Sherbrooke. Programme coopératif, stages intégrés. Ingénierie, sciences, gestion.","Licence avec bonne moyenne.","Français","2027-03-01","https://www.usherbrooke.ca/admission/"),
A("univ-lyon1.fr","Université Claude Bernard Lyon 1","Admission Lyon 1 Master 2027","Candidature en master à Lyon 1. Sciences, santé, ingénierie, sport. Campus de la Doua, Lyon.","Licence en sciences ou santé.","Français (B2+)","2027-05-31","https://www.univ-lyon1.fr/formation/candidature-et-inscription"),
A("u-bordeaux.fr","Université de Bordeaux","Admission Bordeaux Master 2027","Candidature en master à l'Université de Bordeaux. Vin, santé, laser, environnement, droit.","Licence ou équivalent.","Français (B2+)","2027-05-31","https://www.u-bordeaux.fr/formation/candidater-s-inscrire"),
A("univ-amu.fr","Aix-Marseille Université","Admission AMU Master 2027","Candidature en master à AMU, plus grande université francophone. Sciences, droit, économie, lettres. Marseille.","Licence ou équivalent.","Français (B2+)","2027-05-31","https://www.univ-amu.fr/fr/public/candidater"),
A("unistra.fr","Université de Strasbourg","Admission Strasbourg Master 2027","Candidature en master à l'Université de Strasbourg. 4 prix Nobel. Chimie, physique, droit européen, biotechnologie.","Licence ou équivalent.","Français (B2+)","2027-05-31","https://www.unistra.fr/formation/admission-inscription"),

A("um5.ac.ma","Université Mohammed V","Admission UM5 Rabat Master 2027","Candidature en master à l'UM5 de Rabat, meilleure université du Maroc. Sciences, ingénierie, droit, économie, lettres.","Licence ou équivalent. Concours ou sélection sur dossier.","Français et arabe","2027-07-31","https://www.um5.ac.ma/"),
A("uca.ac.ma","Université Cadi Ayyad","Admission UCA Marrakech Master 2027","Candidature en master à l'UCA de Marrakech. Sciences, ingénierie, tourisme, environnement.","Licence ou équivalent.","Français et arabe","2027-07-31","https://www.uca.ma/"),
A("ucad.sn","UCAD","Admission UCAD Dakar Master 2027","Candidature en master à l'UCAD (Université Cheikh Anta Diop) de Dakar, plus grande université d'Afrique de l'Ouest francophone.","Licence ou équivalent. Dossier ou concours.","Français","2027-09-30","https://www.ucad.sn/"),
A("unilu.ac.cd","UNILU","Admission UNILU Master 2027 — Lubumbashi","Candidature en master à l'Université de Lubumbashi, RDC. Sciences, ingénierie, médecine, droit, économie.","Licence ou équivalent.","Français","2027-09-30","https://www.unilu.ac.cd/"),
A("unikin.ac.cd","UNIKIN","Admission UNIKIN Master 2027 — Kinshasa","Candidature en master à l'Université de Kinshasa, plus grande université de la RDC. Médecine, sciences, droit, polytechnique.","Licence ou équivalent.","Français","2027-09-30","https://www.unikin.ac.cd/"),

// ══════════════════════════════════════════════
// BLOC 4 — CONCOURS SUPPLÉMENTAIRES (50)
// ══════════════════════════════════════════════

C("fonction-publique.bj","Ministère de la Santé Bénin","Concours Agents de Santé Bénin 2027","Concours de recrutement d'agents de santé au Bénin. Infirmiers, sages-femmes, techniciens de laboratoire, pharmaciens. Fonction publique.","Diplôme de santé reconnu au Bénin. Nationalité béninoise. Âge limite selon le corps.","Français","2027-06-30","https://www.gouv.bj/",["nationalite","medical","casier"]),
C("fonction-publique.bj","Ministère de l'Éducation Bénin","Concours Enseignants Bénin 2027","Concours de recrutement d'enseignants au Bénin. Primaire (CEAP/CAP) et secondaire (CAPES/BAPES). Mathématiques, français, sciences.","Diplôme d'enseignement ou licence dans la discipline. Nationalité béninoise.","Français","2027-06-30","https://www.gouv.bj/",["nationalite","casier"]),
C("fonction-publique.bj","Police Républicaine Bénin","Concours Police Républicaine Bénin 2027","Concours de recrutement d'officiers et agents de la police républicaine du Bénin. Sécurité, maintien de l'ordre.","Nationalité béninoise. 18-30 ans. Aptitude physique. Bac minimum pour agents.","Français","2027-06-30","https://www.gouv.bj/",["nationalite","medical","casier","photo"]),
C("fonction-publique.bj","Douanes Bénin","Concours Douanes Bénin 2027","Concours de recrutement de douaniers au Bénin. Inspecteurs et contrôleurs des douanes. Administration fiscale.","Nationalité béninoise. Licence en droit, économie ou commerce. Aptitude physique.","Français","2027-06-30","https://www.gouv.bj/",["nationalite","medical","casier"]),
C("fonction-publique.bj","Eaux et Forêts Bénin","Concours Eaux et Forêts Bénin 2027","Concours de recrutement d'agents des eaux et forêts au Bénin. Protection de l'environnement, parcs nationaux, faune.","Nationalité béninoise. Diplôme en environnement, foresterie ou agronomie.","Français","2027-06-30","https://www.gouv.bj/",["nationalite","medical","casier"]),
C("fonction-publique.bj","Magistrature Bénin","Concours Magistrature Bénin 2027","Concours d'entrée à l'École Nationale de Magistrature du Bénin (ENAM). Formation de juges et procureurs.","Maîtrise en droit. Nationalité béninoise. 25-40 ans.","Français","2027-06-30","https://www.gouv.bj/",["nationalite","casier"]),
C("fonction-publique.bj","Greffiers Bénin","Concours Greffiers Bénin 2027","Concours de recrutement de greffiers au Bénin. Administration judiciaire, procédures, rédaction d'actes.","Licence en droit. Nationalité béninoise. 18-35 ans.","Français","2027-06-30","https://www.gouv.bj/",["nationalite","casier"]),
C("fonction-publique.bj","Trésor Public Bénin","Concours Trésor Public Bénin 2027","Concours de recrutement au Trésor public du Bénin. Gestion des finances publiques, comptabilité de l'État.","Licence en comptabilité, finance ou économie. Nationalité béninoise.","Français","2027-06-30","https://www.gouv.bj/",["nationalite","casier"]),
C("fonction-publique.bj","Impôts Bénin","Concours Impôts Bénin 2027","Concours de recrutement aux Impôts du Bénin. Administration fiscale, contrôle, recouvrement.","Licence en droit fiscal, économie ou comptabilité. Nationalité béninoise.","Français","2027-06-30","https://www.gouv.bj/",["nationalite","casier"]),

C("fonction-publique.ci","Fonction Publique CI","Concours Fonction Publique Côte d'Ivoire 2027","Concours de la fonction publique ivoirienne. Administration, enseignement, santé, finances. Tous niveaux.","Nationalité ivoirienne. Diplôme requis selon le corps. Âge limite.","Français","2027-06-30","https://www.fonctionpublique.gouv.ci/",["nationalite","casier"]),
C("fonction-publique.sn","Fonction Publique Sénégal","Concours Fonction Publique Sénégal 2027","Concours de la fonction publique sénégalaise. Administration, enseignement, santé, défense. Tous niveaux.","Nationalité sénégalaise. Diplôme requis selon le corps.","Français","2027-06-30","https://www.fonctionpublique.gouv.sn/",["nationalite","casier"]),
C("minfopra.gov.cm","Fonction Publique Cameroun","Concours Fonction Publique Cameroun 2027","Concours de la fonction publique camerounaise. Administration, santé, enseignement, police, gendarmerie.","Nationalité camerounaise. Diplôme requis selon le corps.","Français et/ou anglais","2027-06-30","https://www.minfopra.gov.cm/",["nationalite","casier"]),
C("fonction-publique.tg","Fonction Publique Togo","Concours Fonction Publique Togo 2027","Concours de la fonction publique togolaise. Administration, santé, éducation. Tous niveaux.","Nationalité togolaise. Diplôme requis.","Français","2027-06-30","https://www.fonction-publique.gouv.tg/",["nationalite","casier"]),
C("mfpra.gov.bf","Fonction Publique Burkina Faso","Concours Fonction Publique Burkina 2027","Concours de la fonction publique burkinabè. Administration, santé, enseignement, mines.","Nationalité burkinabè. Diplôme requis.","Français","2027-06-30","https://www.fonction-publique.gov.bf/",["nationalite","casier"]),
C("mfp.gov.ml","Fonction Publique Mali","Concours Fonction Publique Mali 2027","Concours de la fonction publique malienne. Administration, santé, éducation, défense.","Nationalité malienne. Diplôme requis.","Français","2027-06-30","https://www.fonction-publique.gov.ml/",["nationalite","casier"]),
C("mfptra.gov.ne","Fonction Publique Niger","Concours Fonction Publique Niger 2027","Concours de la fonction publique nigérienne. Administration, santé, éducation, hydraulique.","Nationalité nigérienne. Diplôme requis.","Français","2027-06-30","https://www.fonction-publique.gov.ne/",["nationalite","casier"]),
C("mfp.gov.gn","Fonction Publique Guinée","Concours Fonction Publique Guinée 2027","Concours de la fonction publique guinéenne. Administration, mines, santé, éducation.","Nationalité guinéenne. Diplôme requis.","Français","2027-06-30","https://www.fonction-publique.gov.gn/",["nationalite","casier"]),

C("enam.bj","ENAM","Concours ENAM Bénin 2027","Concours d'entrée à l'École Nationale d'Administration et de Magistrature du Bénin. Administration, diplomatie, finances.","Licence minimum. Nationalité béninoise ou CEDEAO. Âge limite 30 ans.","Français","2027-06-30","https://www.enam.bj/",["nationalite","casier"]),
C("eneam.uac.bj","ENEAM","Concours ENEAM 2027 — Statistique et Économie","Concours d'entrée à l'ENEAM de l'UAC. Statistique, planification, économie appliquée. Formation de cadres statisticiens.","Bac ou licence selon le cycle. Nationalité CEDEAO. Bon niveau en mathématiques.","Français","2027-06-30","https://www.eneam.bj/",["nationalite"]),
C("epac.uac.bj","EPAC","Concours EPAC 2027 — Ingénieur","Concours d'entrée à l'EPAC de l'UAC. Génie civil, informatique, électrique, mécanique, production et santé animale.","Bac scientifique C, D ou E. Concours en maths, physique, chimie. Âge limite.","Français","2027-06-30","https://www.epac.uac.bj/",["nationalite"]),
C("faseg.uac.bj","FASEG","Concours FASEG UAC 2027 — Sciences Économiques","Concours d'entrée à la FASEG de l'UAC. Sciences économiques, gestion, management, finance.","Bac (toutes séries). Concours écrit en culture générale, maths, économie.","Français","2027-06-30","https://www.uac.bj/",["nationalite"]),

// Concours internationaux
C("concours-ena.fr","ENA/INSP France","Concours INSP 2027 — Administration France","Concours de l'Institut National du Service Public (ex-ENA). Formation des hauts fonctionnaires français. Ouvert aux étrangers pour le cycle international.","Master en droit, économie ou sciences politiques. Ou fonctionnaire étranger pour le cycle international.","Français (C1+)","2027-10-31","https://www.insp.gouv.fr/",["diplome"]),
C("ec.europa.eu","Union Européenne","Concours EPSO 2027 — Institutions Européennes","Concours de l'Office Européen de Sélection du Personnel. Administrateurs, assistants, traducteurs pour les institutions UE. Bruxelles, Luxembourg.","Licence minimum. Nationalité UE (ou pays associés pour certains profils). 2+ langues UE.","2 langues UE minimum","2027-06-30","https://epso.europa.eu/",["langue"]),
C("banquemondiale.org","Banque Mondiale","Young Professionals Program — Banque Mondiale 2027","Programme Jeunes Professionnels de la Banque Mondiale. Recrutement de jeunes talents pour postes de cadre. Washington DC.","Master ou doctorat. Moins de 32 ans. 3+ ans d'expérience. Nationalité d'un pays membre.","Anglais courant, 2e langue appréciée","2027-06-30","https://www.worldbank.org/en/about/careers/programs-and-internships/young-professionals-program",["recommandation"]),
C("afdb.org","BAD","Programme Jeunes Professionnels BAD 2027","Programme Jeunes Professionnels de la Banque Africaine de Développement. Recrutement pour postes à Abidjan et dans les bureaux pays.","Master minimum. 32 ans maximum. Nationalité d'un pays membre de la BAD.","Français et anglais","2027-06-30","https://www.afdb.org/en/careers",["recommandation"]),

// ══════════════════════════════════════════════
// BLOC 5 — BOURSES & EMPLOI RESTANTS (40)
// ══════════════════════════════════════════════

// Bourses Commonwealth
B("cscuk.fcdo.gov.uk","Commonwealth","Bourse Commonwealth Master 2027 — UK","Bourses du Commonwealth pour master au Royaume-Uni. Frais, billet, allocation. Pour citoyens de pays du Commonwealth (incluant Nigeria, Ghana, Cameroun).","Licence avec mention. Nationalité d'un pays du Commonwealth. Expérience professionnelle appréciée.","Anglais","2027-01-15","https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/",["recommandation"]),
B("cscuk.fcdo.gov.uk","Commonwealth","Bourse Commonwealth PhD 2027 — UK","Bourses du Commonwealth pour doctorat au Royaume-Uni. 3 ans de financement complet. Pour citoyens de pays du Commonwealth.","Master avec mention. Nationalité du Commonwealth. Projet de recherche clair.","Anglais","2027-01-15","https://cscuk.fcdo.gov.uk/scholarships/commonwealth-phd-scholarships/",["recommandation","projet"]),

// Fulbright
B("fulbright.org","Gouvernement Américain","Bourse Fulbright 2027 — États-Unis","Programme Fulbright pour master et doctorat aux USA. Frais, allocation, billet, assurance. Plus de 160 pays éligibles dont le Bénin.","Licence avec excellence. Nationalité non-américaine. Projet d'études clair.","Anglais (TOEFL 80+)","2027-10-15","https://foreign.fulbrightonline.org/",["recommandation"]),

// Emploi supplémentaires Bénin
E("boad.org","BOAD","BOAD — Postes Banque de Développement 2027","Postes à la BOAD (Banque Ouest-Africaine de Développement). Financement de projets, études économiques, gestion de portefeuille. Siège à Lomé.","Master en finance, économie, ingénierie ou droit. Nationalité UEMOA.","Français courant","2027-06-30","https://www.boad.org/carrieres/",["nationalite"]),
E("bceao.int","BCEAO","BCEAO — Postes Banque Centrale 2027","Postes à la BCEAO (Banque Centrale des États de l'Afrique de l'Ouest). Politique monétaire, supervision bancaire, systèmes de paiement. Dakar.","Master en économie, finance, statistique ou informatique. Nationalité UEMOA.","Français courant","2027-06-30","https://www.bceao.int/fr/content/opportunites-de-carriere",["nationalite"]),
E("bidc-ebid.org","BIDC","BIDC — Postes Banque d'Investissement CEDEAO 2027","Postes à la BIDC (Banque d'Investissement et de Développement de la CEDEAO). Financement de projets en Afrique de l'Ouest. Lomé.","Master en finance, économie ou ingénierie. Nationalité CEDEAO.","Français et anglais","2027-06-30","https://www.bidc-ebid.org/en/careers/",["nationalite"]),
E("portcotonou.com","Port de Cotonou","Port Autonome de Cotonou — Postes 2027","Postes au Port Autonome de Cotonou. Gestion portuaire, logistique, transit, douanes, manutention, sécurité maritime.","Diplôme en logistique maritime, commerce international ou ingénierie. Nationalité béninoise.","Français courant","2027-06-30","https://www.portcotonou.com/",["nationalite"]),
E("asecna.org","ASECNA","ASECNA — Postes Aviation Afrique 2027","Postes à l'ASECNA (Agence pour la Sécurité de la Navigation Aérienne en Afrique). Contrôle aérien, météo, télécommunications. 17 pays membres.","Diplôme en aéronautique, météorologie, télécoms ou électronique. Nationalité d'un État membre.","Français courant","2027-06-30","https://www.asecna.aero/",["nationalite"]),
E("cimbenin.com","CIM Bénin","CIM Bénin — Postes Maritime 2027","Postes au Conseil des Investisseurs Privés et au secteur maritime béninois. Consignation, transit, commerce international.","Diplôme en commerce international, logistique ou droit maritime.","Français courant","2027-06-30","https://www.cimbenin.com/"),
E("otr.tg","OTR Togo","OTR Togo — Postes Fiscalité 2027","Postes à l'Office Togolais des Recettes. Administration fiscale et douanière du Togo. Contrôle, recouvrement, informatique.","Diplôme en fiscalité, droit, économie ou comptabilité. Nationalité togolaise.","Français courant","2027-06-30","https://www.otr.tg/",["nationalite"]),

// Bourses finales pour atteindre le quota
B("opportunites.campusfrance.org","Campus France","Bourse d'Excellence Eiffel 2027 — Master","Programme de bourses Eiffel pour master en France. 1 181 EUR/mois + assurance + logement. Sciences, économie, droit, sciences politiques.","Moins de 30 ans (master). Université d'origine dans un pays prioritaire. Dossier présenté par l'établissement français.","Français ou anglais","2027-01-12","https://www.campusfrance.org/fr/le-programme-de-bourses-eiffel",["recommandation"]),
B("daad.de","DAAD","Bourse DAAD In-Country/In-Region Afrique 2027","Bourses DAAD pour master et doctorat dans des universités africaines partenaires. Allocation, frais, recherche. Études dans votre région.","Nationalité africaine. Admis dans un programme partenaire DAAD en Afrique.","Anglais ou français","2027-10-15","https://www.daad.de/en/studying-in-germany/scholarships/",["recommandation"]),
B("opportunites.auf.org","AUF","Bourse AUF Mobilité 2027 — Francophonie","Bourses de mobilité de l'AUF pour étudiants francophones. Master et doctorat dans les universités membres. 800+ universités partenaires.","Nationalité d'un pays francophone. Inscrit dans une université membre de l'AUF.","Français","2027-03-31","https://www.auf.org/nos-actions/toutes-nos-actions/bourses-de-mobilite/"),
B("ostscholarships.com","Gouvernement Hongrois","Bourse Stipendium Hungaricum 2027 — Hongrie","Bourses du gouvernement hongrois. Licence, master, doctorat. Frais, logement, allocation, assurance. 85 pays partenaires dont pays africains.","Nationalité d'un pays partenaire. Diplôme requis pour le niveau visé.","Anglais ou hongrois","2027-01-15","https://stipendiumhungaricum.hu/",["passeport"]),
B("edupoland.pl","Gouvernement Polonais","Bourse NAWA Poland 2027 — Pologne","Bourses NAWA du gouvernement polonais pour master et doctorat. Sciences, ingénierie, médecine. Allocation et frais.","Nationalité d'un pays en développement. Diplôme requis.","Anglais ou polonais","2027-03-31","https://nawa.gov.pl/en/students/foreign-students/",["passeport"]),
B("mfa.gov.cz","Gouvernement Tchèque","Bourse Gouvernement Tchèque 2027","Bourses du gouvernement tchèque pour étudiants de pays en développement. Licence, master, doctorat. Frais + allocation + logement.","Nationalité d'un pays en développement. Moins de 26 ans (licence) ou 35 ans (master/doctorat).","Anglais ou tchèque","2027-09-30","https://www.studyin.cz/scholarships/",["passeport"]),
B("romaniascholarships.ro","Gouvernement Roumain","Bourse Gouvernement Roumain 2027","Bourses du gouvernement roumain pour étudiants étrangers. Licence, master, doctorat. Frais + allocation. Cours de roumain fournis.","Nationalité non-UE. Diplôme requis pour le niveau.","Roumain (cours fournis) ou anglais","2027-03-15","https://www.mae.ro/en/node/10251",["passeport"]),

// Emploi Bénin derniers
E("mtca.bj","MTCA Bénin","MTCA — Postes Tourisme Bénin 2027","Postes au Ministère du Tourisme, de la Culture et des Arts du Bénin. Promotion touristique, patrimoine culturel, musées, festivals.","Diplôme en tourisme, communication, arts ou patrimoine. Nationalité béninoise.","Français courant","2027-06-30","https://www.tourisme.gouv.bj/",["nationalite"]),
E("anpe.bj","ANPE Bénin","ANPE — Offres d'emploi Bénin 2027","Offres d'emploi via l'Agence Nationale pour l'Emploi du Bénin. Tous secteurs : administration, BTP, commerce, santé, IT. Plateforme nationale.","Variable selon les postes. Inscription à l'ANPE.","Français","2027-12-31","https://www.anpe.bj/"),
E("snaforij.bj","SNAFORIJ","SNAFORIJ — Postes Formation Juridique Bénin 2027","Postes au Service National de la Formation Juridique du Bénin. Formation des greffiers, huissiers, notaires. Administration judiciaire.","Maîtrise en droit. Nationalité béninoise.","Français","2027-06-30","https://www.justice.gouv.bj/",["nationalite"]),
];

async function main() {
  console.log(`Lot 6 — Total à insérer : ${ALL.length}`);
  let ins = 0, skip = 0;
  for (const o of ALL) {
    const ex = await prisma.opportunite.findFirst({ where: { intitule: o.intitule, organisme: o.organisme } });
    if (ex) { skip++; continue; }
    await prisma.opportunite.create({
      data: { type:o.type,source:o.source,organisme:o.organisme,intitule:o.intitule,description:o.description,langueDetectee:o.langueDetectee,conditions:o.conditions,piecesExigees:o.piecesExigees,exigenceLangue:o.exigenceLangue,dateLimite:new Date(o.dateLimite),lien:o.lien,canalCandidature:o.canalCandidature,cibleCandidature:o.cibleCandidature,statut:"publiee",actif:true,confianceDateLimite:0.85,sourceDateLimite:"recherche web" },
    });
    ins++;
    if (ins % 50 === 0) console.log(`  ... ${ins}`);
  }
  const tot = await prisma.opportunite.count({ where: { statut: "publiee" } });
  console.log(`\nInsérées: ${ins} | Skip: ${skip} | Total publiées: ${tot}`);
}
main().catch(console.error).finally(() => prisma.$disconnect());
export {};
