import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

function p(type: string, extras: string[] = []): string {
  const base: Record<string, any[]> = {
    BOURSE: [{nom:"Lettre de motivation",type:"lettre",categorie:"generable",obligatoire:true},{nom:"CV",type:"cv",categorie:"generable",obligatoire:true},{nom:"Relevés de notes",type:"releves",categorie:"personnel",obligatoire:true}],
    EMPLOI: [{nom:"Lettre de motivation",type:"lettre",categorie:"generable",obligatoire:true},{nom:"CV",type:"cv",categorie:"generable",obligatoire:true}],
    ADMISSION: [{nom:"Lettre de motivation",type:"lettre",categorie:"generable",obligatoire:true},{nom:"Relevés de notes",type:"releves",categorie:"personnel",obligatoire:true},{nom:"Diplômes",type:"diplome",categorie:"personnel",obligatoire:true}],
    CONCOURS: [{nom:"Diplômes",type:"diplome",categorie:"personnel",obligatoire:true},{nom:"Acte de naissance",type:"etat_civil",categorie:"personnel",obligatoire:true}],
  };
  const arr = [...(base[type] || base.EMPLOI)];
  const map: Record<string,any> = {
    recommandation:{nom:"Lettres de recommandation",type:"recommandation",categorie:"personnel",obligatoire:true},
    passeport:{nom:"Passeport",type:"passeport",categorie:"personnel",obligatoire:true},
    langue:{nom:"Certificat de langue",type:"langue",categorie:"personnel",obligatoire:true},
    projet:{nom:"Projet de recherche",type:"projet",categorie:"generable",obligatoire:true},
    medical:{nom:"Certificat médical",type:"medical",categorie:"personnel",obligatoire:true},
    nationalite:{nom:"Certificat de nationalité",type:"nationalite",categorie:"personnel",obligatoire:true},
    casier:{nom:"Casier judiciaire",type:"casier",categorie:"personnel",obligatoire:true},
    photo:{nom:"Photo d identité",type:"photo",categorie:"personnel",obligatoire:true},
    diplome:{nom:"Diplômes certifiés",type:"diplome",categorie:"personnel",obligatoire:true},
  };
  for (const e of extras) if (map[e]) arr.push(map[e]);
  return JSON.stringify(arr);
}

type O = {type:string;source:string;organisme:string;intitule:string;description:string;langueDetectee:string;conditions:string;piecesExigees:string;exigenceLangue:string;dateLimite:string;lien:string;canalCandidature:string;cibleCandidature:string};

const ALL: O[] = [

// ═══ EMPLOI — VIE (Volontariat International en Entreprise) ═══
{type:"EMPLOI",source:"civiweb.com",organisme:"Business France",intitule:"VIE — Volontariat International en Entreprise 2027 (général)",description:"Le VIE permet aux jeunes de 18-28 ans de travailler à l'étranger pour une entreprise française pendant 6 à 24 mois. Indemnité de 1 500 à 3 800 EUR/mois selon le pays. Plus de 10 000 missions/an.",langueDetectee:"fr",conditions:"18-28 ans. Nationalité française ou européenne. Disponibilité pour une mission à l'étranger.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français et langue du pays d'accueil",dateLimite:"2027-06-30",lien:"https://www.civiweb.com/",canalCandidature:"formulaire",cibleCandidature:"https://www.civiweb.com/"},
{type:"EMPLOI",source:"civiweb.com",organisme:"Business France",intitule:"VIE TotalEnergies — Afrique 2027",description:"Missions VIE chez TotalEnergies en Afrique : ingénierie, HSE, supply chain. Indemnité + avantages. Nombreuses missions au Nigeria, Angola, Congo, Cameroun.",langueDetectee:"fr",conditions:"18-28 ans. Formation d'ingénieur ou commerce.",piecesExigees:p("EMPLOI"),exigenceLangue:"Anglais et français",dateLimite:"2027-06-30",lien:"https://www.civiweb.com/",canalCandidature:"formulaire",cibleCandidature:"https://www.civiweb.com/"},
{type:"EMPLOI",source:"civiweb.com",organisme:"Business France",intitule:"VIE Société Générale — Afrique 2027",description:"Missions VIE chez Société Générale dans ses filiales africaines. Banque de détail, finance d'entreprise, conformité, IT.",langueDetectee:"fr",conditions:"18-28 ans. Master en finance, économie ou IT.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant",dateLimite:"2027-06-30",lien:"https://www.civiweb.com/",canalCandidature:"formulaire",cibleCandidature:"https://www.civiweb.com/"},

// ═══ EMPLOI — LUXE & MODE ═══
{type:"EMPLOI",source:"kering.com",organisme:"Kering",intitule:"Kering — Graduate Programme 2027 (Gucci, YSL, Balenciaga)",description:"Programme pour diplômés chez Kering, groupe de luxe (Gucci, Saint Laurent, Balenciaga, Bottega Veneta). Rotations en marketing, digital, supply chain, retail.",langueDetectee:"fr",conditions:"Master en commerce, marketing, mode ou ingénierie. 0-2 ans d'expérience.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais et français courants",dateLimite:"2027-04-30",lien:"https://www.kering.com/en/talent/",canalCandidature:"formulaire",cibleCandidature:"https://www.kering.com/en/talent/"},
{type:"EMPLOI",source:"hermes.com",organisme:"Hermès",intitule:"Hermès — Jeunes Talents 2027",description:"Postes pour jeunes diplômés chez Hermès. Artisanat, maroquinerie, retail, digital, supply chain. Maison de luxe française emblématique.",langueDetectee:"fr",conditions:"Master en commerce, artisanat, ingénierie ou design. Sensibilité au luxe.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant, anglais apprécié",dateLimite:"2027-05-31",lien:"https://www.hermes.com/fr/fr/talents/",canalCandidature:"formulaire",cibleCandidature:"https://www.hermes.com/fr/fr/talents/"},
{type:"EMPLOI",source:"chanel.com",organisme:"Chanel",intitule:"Chanel — Graduate Programme 2027",description:"Programme pour diplômés chez Chanel. Mode, beauté, horlogerie-joaillerie. Postes en marketing, finance, digital, retail à Paris et dans le monde.",langueDetectee:"fr",conditions:"Master récent. Passion pour le luxe et l'excellence.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Français et anglais courants",dateLimite:"2027-05-31",lien:"https://www.chanel.com/fr/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.chanel.com/fr/careers/"},

// ═══ EMPLOI — BANQUES MONDIALES ═══
{type:"EMPLOI",source:"credit-suisse.com",organisme:"UBS (ex Credit Suisse)",intitule:"UBS — Graduate Talent Programme 2027",description:"Programme pour diplômés chez UBS, plus grande banque suisse. Wealth management, investment banking, asset management. Bureaux mondiaux.",langueDetectee:"fr",conditions:"Master en finance, économie, mathématiques ou informatique.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2026-11-30",lien:"https://www.ubs.com/global/en/careers/graduates.html",canalCandidature:"formulaire",cibleCandidature:"https://www.ubs.com/global/en/careers/graduates.html"},
{type:"EMPLOI",source:"morganstanley.com",organisme:"Morgan Stanley",intitule:"Morgan Stanley — Graduate Programme 2027",description:"Programme de 2 ans chez Morgan Stanley. Investment banking, equity research, trading, technology. Bureaux à NYC, Londres, Hong Kong.",langueDetectee:"fr",conditions:"Master en finance, économie, mathématiques ou informatique.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2026-10-31",lien:"https://www.morganstanley.com/people/students-graduates",canalCandidature:"formulaire",cibleCandidature:"https://www.morganstanley.com/people/students-graduates"},
{type:"EMPLOI",source:"barclays.com",organisme:"Barclays",intitule:"Barclays — Graduate Programme 2027 (UK/Africa)",description:"Programme graduate chez Barclays. Investment banking, corporate banking, technology. Présence historique en Afrique (Absa Group).",langueDetectee:"fr",conditions:"Master en finance, économie ou informatique.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2026-11-30",lien:"https://home.barclays/careers/students-and-graduates/",canalCandidature:"formulaire",cibleCandidature:"https://home.barclays/careers/students-and-graduates/"},
{type:"EMPLOI",source:"hsbc.com",organisme:"HSBC",intitule:"HSBC — Graduate Programme 2027 (Global)",description:"Programme de 18-24 mois chez HSBC, la plus grande banque internationale. Présence dans 64 pays. Retail banking, wealth, commercial, global banking.",langueDetectee:"fr",conditions:"Master récent. Mobilité internationale.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2026-11-30",lien:"https://www.hsbc.com/careers/students-and-graduates",canalCandidature:"formulaire",cibleCandidature:"https://www.hsbc.com/careers/students-and-graduates"},
{type:"EMPLOI",source:"standardchartered.com",organisme:"Standard Chartered",intitule:"Standard Chartered — International Graduate 2027 (Afrique)",description:"Programme graduate chez Standard Chartered, banque britannique forte en Afrique (15 pays). 18 mois de rotations en banking, digital, risk management.",langueDetectee:"fr",conditions:"Master récent. Intérêt pour l'Afrique et les marchés émergents.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-03-31",lien:"https://www.sc.com/en/careers/early-careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.sc.com/en/careers/early-careers/"},

// ═══ EMPLOI — MINES & RESSOURCES NATURELLES ═══
{type:"EMPLOI",source:"rio-tinto.com",organisme:"Rio Tinto",intitule:"Rio Tinto — Graduate Programme 2027 (Mines Afrique)",description:"Programme pour diplômés chez Rio Tinto, géant minier. Mines en Guinée (bauxite), Madagascar, Afrique du Sud. Ingénierie minière, géologie, environnement.",langueDetectee:"fr",conditions:"Master en ingénierie minière, géologie, métallurgie ou environnement.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant, français pour la Guinée",dateLimite:"2027-03-31",lien:"https://www.riotinto.com/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.riotinto.com/careers"},
{type:"EMPLOI",source:"barrick.com",organisme:"Barrick Gold",intitule:"Barrick Gold — Postes Mines Afrique 2027",description:"Postes chez Barrick Gold en Afrique. Mines d'or au Mali, Tanzanie, RDC, Côte d'Ivoire. Ingénierie, géologie, environnement, sécurité.",langueDetectee:"fr",conditions:"Diplôme en ingénierie minière, géologie ou environnement. Expérience terrain appréciée.",piecesExigees:p("EMPLOI"),exigenceLangue:"Anglais et/ou français",dateLimite:"2027-06-30",lien:"https://www.barrick.com/English/careers/default.aspx",canalCandidature:"formulaire",cibleCandidature:"https://www.barrick.com/English/careers/default.aspx"},
{type:"EMPLOI",source:"anglogoldashanti.com",organisme:"AngloGold Ashanti",intitule:"AngloGold Ashanti — Graduate Programme Afrique 2027",description:"Programme pour diplômés chez AngloGold Ashanti, producteur d'or majeur en Afrique. Mines au Ghana, Guinée, Tanzanie. Ingénierie, géologie, HSE.",langueDetectee:"fr",conditions:"Master en ingénierie minière, géologie, métallurgie ou environnement.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://www.anglogoldashanti.com/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.anglogoldashanti.com/careers/"},

// ═══ EMPLOI — STARTUPS AFRICAINES ═══
{type:"EMPLOI",source:"wave.com",organisme:"Wave",intitule:"Wave — Postes Fintech Sénégal/CI 2027",description:"Postes chez Wave, licorne fintech d'Afrique de l'Ouest. Mobile money à faible coût. Ingénierie, produit, opérations. Bureaux à Dakar et Abidjan.",langueDetectee:"fr",conditions:"Diplôme en informatique, ingénierie ou commerce. Expérience fintech appréciée.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français et anglais",dateLimite:"2027-06-30",lien:"https://www.wave.com/en/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.wave.com/en/careers/"},
{type:"EMPLOI",source:"jumia.com",organisme:"Jumia",intitule:"Jumia — Postes E-commerce Afrique 2027",description:"Postes chez Jumia, 1re plateforme e-commerce d'Afrique. Présent dans 11 pays. Tech, logistique, marketing, opérations. Siège à Lagos.",langueDetectee:"fr",conditions:"Diplôme en informatique, logistique, marketing ou commerce.",piecesExigees:p("EMPLOI"),exigenceLangue:"Anglais et/ou français",dateLimite:"2027-06-30",lien:"https://group.jumia.com/careers/",canalCandidature:"formulaire",cibleCandidature:"https://group.jumia.com/careers/"},
{type:"EMPLOI",source:"interswitch.com",organisme:"Interswitch",intitule:"Interswitch — Postes Fintech Nigeria 2027",description:"Postes chez Interswitch, infrastructure de paiement leader en Afrique. Domaines : ingénierie, cybersécurité, produit, data. Siège à Lagos.",langueDetectee:"fr",conditions:"Diplôme en informatique ou ingénierie. Expérience en fintech ou paiements appréciée.",piecesExigees:p("EMPLOI"),exigenceLangue:"Anglais courant",dateLimite:"2027-06-30",lien:"https://www.interswitchgroup.com/career",canalCandidature:"formulaire",cibleCandidature:"https://www.interswitchgroup.com/career"},
{type:"EMPLOI",source:"mpower.africa",organisme:"M-KOPA",intitule:"M-KOPA — Postes Énergie Solaire Afrique 2027",description:"Postes chez M-KOPA, leader de l'énergie solaire pay-as-you-go en Afrique. Ingénierie, data, ventes, opérations. Kenya, Ouganda, Nigeria, Ghana.",langueDetectee:"fr",conditions:"Diplôme en ingénierie, commerce ou data science. Passion pour l'énergie propre.",piecesExigees:p("EMPLOI"),exigenceLangue:"Anglais courant",dateLimite:"2027-06-30",lien:"https://www.m-kopa.com/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.m-kopa.com/careers"},
{type:"EMPLOI",source:"moniepoint.com",organisme:"Moniepoint",intitule:"Moniepoint — Postes Fintech Nigeria 2027",description:"Postes chez Moniepoint, infrastructure de paiement et banking pour PME en Afrique. Ingénierie backend, mobile, data. Croissance rapide.",langueDetectee:"fr",conditions:"Diplôme en informatique ou ingénierie. Compétences en Java, Kotlin ou Python.",piecesExigees:p("EMPLOI"),exigenceLangue:"Anglais courant",dateLimite:"2027-06-30",lien:"https://moniepoint.com/careers",canalCandidature:"formulaire",cibleCandidature:"https://moniepoint.com/careers"},

// ═══ ADMISSION — ÉCOLES DE COMMERCE ═══
{type:"ADMISSION",source:"insead.edu",organisme:"INSEAD",intitule:"Admission MBA INSEAD 2027 — France/Singapour",description:"Candidature au MBA d'INSEAD, classé n°1 mondial par le Financial Times. Programme de 10 mois à Fontainebleau et Singapour. Très diversifié internationalement.",langueDetectee:"fr",conditions:"Licence. 3-7 ans d'expérience professionnelle. GMAT ou GRE. 2 lettres de recommandation.",piecesExigees:p("ADMISSION",["recommandation","langue"]),exigenceLangue:"Anglais courant + 2e langue requise",dateLimite:"2027-01-10",lien:"https://www.insead.edu/master-programmes/mba/admissions",canalCandidature:"formulaire",cibleCandidature:"https://www.insead.edu/master-programmes/mba/admissions"},
{type:"ADMISSION",source:"london.edu",organisme:"London Business School",intitule:"Admission MBA London Business School 2027",description:"Candidature au MBA de LBS, régulièrement classé n°1 en Europe. 15-21 mois à Londres. Plus de 90 nationalités représentées.",langueDetectee:"fr",conditions:"Licence. 3+ ans d'expérience professionnelle. GMAT ou GRE.",piecesExigees:p("ADMISSION",["recommandation","langue"]),exigenceLangue:"Anglais (IELTS 7.5+ ou TOEFL 105+)",dateLimite:"2027-01-09",lien:"https://www.london.edu/programmes/mba/admissions",canalCandidature:"formulaire",cibleCandidature:"https://www.london.edu/programmes/mba/admissions"},
{type:"ADMISSION",source:"iese.edu",organisme:"IESE Business School",intitule:"Admission MBA IESE 2027 — Barcelone",description:"Candidature au MBA d'IESE Barcelona, top 5 européen. 19 mois en méthode de cas. Campus à Barcelone, Madrid, New York, Munich, São Paulo.",langueDetectee:"fr",conditions:"Licence. 3+ ans d'expérience. GMAT ou GRE.",piecesExigees:p("ADMISSION",["recommandation"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-15",lien:"https://www.iese.edu/mba/admissions/",canalCandidature:"formulaire",cibleCandidature:"https://www.iese.edu/mba/admissions/"},
{type:"ADMISSION",source:"sbs.ox.ac.uk",organisme:"Saïd Business School — Oxford",intitule:"Admission MBA Oxford Saïd 2027",description:"Candidature au MBA d'Oxford Saïd, programme d'un an à Oxford. Entrepreneuriat, finance et social impact. Réseau Oxford mondial.",langueDetectee:"fr",conditions:"Licence. 3+ ans d'expérience. GMAT ou GRE.",piecesExigees:p("ADMISSION",["recommandation","langue"]),exigenceLangue:"Anglais (IELTS 7.5+)",dateLimite:"2027-01-10",lien:"https://www.sbs.ox.ac.uk/programmes/mba/how-to-apply/",canalCandidature:"formulaire",cibleCandidature:"https://www.sbs.ox.ac.uk/programmes/mba/how-to-apply/"},
{type:"ADMISSION",source:"jbs.cam.ac.uk",organisme:"Judge Business School — Cambridge",intitule:"Admission MBA Cambridge Judge 2027",description:"Candidature au MBA de Cambridge Judge, programme d'un an. Innovation, entrepreneuriat et consulting. Réseau Cambridge mondial.",langueDetectee:"fr",conditions:"Licence. 3+ ans d'expérience. GMAT ou GRE.",piecesExigees:p("ADMISSION",["recommandation","langue"]),exigenceLangue:"Anglais (IELTS 7.5+)",dateLimite:"2027-04-30",lien:"https://www.jbs.cam.ac.uk/programmes/mba/",canalCandidature:"formulaire",cibleCandidature:"https://www.jbs.cam.ac.uk/programmes/mba/"},
{type:"ADMISSION",source:"em-lyon.com",organisme:"emlyon business school",intitule:"Admission Master Grande École emlyon 2027",description:"Candidature au Programme Grande École d'emlyon. 2-3 ans de formation en management, finance, entrepreneuriat. Campus à Lyon, Paris, Shanghai, Mumbai.",langueDetectee:"fr",conditions:"Licence ou en cours. Concours d'entrée ou admission sur dossier pour internationaux.",piecesExigees:p("ADMISSION"),exigenceLangue:"Français ou anglais",dateLimite:"2027-04-30",lien:"https://em-lyon.com/en/programme-grande-ecole",canalCandidature:"formulaire",cibleCandidature:"https://em-lyon.com/en/programme-grande-ecole"},
{type:"ADMISSION",source:"kedge.edu",organisme:"KEDGE Business School",intitule:"Admission Master Grande École KEDGE 2027",description:"Candidature au PGE de KEDGE. Campus à Bordeaux, Marseille, Paris, Dakar, Abidjan et Shanghai. Forte présence en Afrique.",langueDetectee:"fr",conditions:"Licence. Admission sur dossier pour internationaux.",piecesExigees:p("ADMISSION"),exigenceLangue:"Français ou anglais",dateLimite:"2027-05-31",lien:"https://www.kedge.edu/",canalCandidature:"formulaire",cibleCandidature:"https://www.kedge.edu/"},

// ═══ ADMISSION — ÉCOLES D'INGÉNIEURS ═══
{type:"ADMISSION",source:"centralesupelec.fr",organisme:"CentraleSupélec",intitule:"Admission Ingénieur CentraleSupélec 2027",description:"Candidature au cycle ingénieur de CentraleSupélec, top école d'ingénieurs française. Formation généraliste de haut niveau. Campus à Gif-sur-Yvette.",langueDetectee:"fr",conditions:"CPGE ou licence scientifique. Concours Centrale-Supélec ou admission sur titre pour internationaux.",piecesExigees:p("ADMISSION",["langue"]),exigenceLangue:"Français B2+ ou anglais C1",dateLimite:"2027-01-15",lien:"https://www.centralesupelec.fr/fr/admissions",canalCandidature:"formulaire",cibleCandidature:"https://www.centralesupelec.fr/fr/admissions"},
{type:"ADMISSION",source:"mines-paristech.fr",organisme:"Mines Paris — PSL",intitule:"Admission Ingénieur Mines Paris 2027",description:"Candidature au cycle ingénieur de Mines Paris — PSL. Top 5 des écoles d'ingénieurs françaises. Géosciences, énergie, matériaux, management.",langueDetectee:"fr",conditions:"CPGE ou licence. Concours commun Mines-Ponts ou admission sur titre.",piecesExigees:p("ADMISSION",["langue"]),exigenceLangue:"Français B2+",dateLimite:"2027-01-31",lien:"https://www.minesparis.psl.eu/formation/",canalCandidature:"formulaire",cibleCandidature:"https://www.minesparis.psl.eu/formation/"},
{type:"ADMISSION",source:"telecom-paris.fr",organisme:"Télécom Paris",intitule:"Admission Ingénieur Télécom Paris 2027",description:"Candidature au cycle ingénieur de Télécom Paris, 1re grande école du numérique en France. IA, cybersécurité, data, réseaux. Membre de IP Paris.",langueDetectee:"fr",conditions:"CPGE ou licence en sciences/informatique. Concours Mines-Télécom ou admission sur titre.",piecesExigees:p("ADMISSION",["langue"]),exigenceLangue:"Français B2+ ou anglais C1",dateLimite:"2027-02-28",lien:"https://www.telecom-paris.fr/fr/ingenieur/comment-integrer",canalCandidature:"formulaire",cibleCandidature:"https://www.telecom-paris.fr/fr/ingenieur/comment-integrer"},
{type:"ADMISSION",source:"enpc.fr",organisme:"École des Ponts ParisTech",intitule:"Admission Ingénieur Ponts ParisTech 2027",description:"Candidature au cycle ingénieur de l'École des Ponts ParisTech, plus ancienne école d'ingénieur du monde (1747). Génie civil, transports, environnement, finance.",langueDetectee:"fr",conditions:"CPGE ou licence. Concours commun Mines-Ponts ou admission sur titre.",piecesExigees:p("ADMISSION",["langue"]),exigenceLangue:"Français B2+",dateLimite:"2027-01-31",lien:"https://www.enpc.fr/admission",canalCandidature:"formulaire",cibleCandidature:"https://www.enpc.fr/admission"},
{type:"ADMISSION",source:"ensam.eu",organisme:"Arts et Métiers",intitule:"Admission Ingénieur Arts et Métiers 2027",description:"Candidature au cycle ingénieur des Arts et Métiers. Ingénierie mécanique, production industrielle, énergie. 8 campus en France + Rabat et Cluny.",langueDetectee:"fr",conditions:"CPGE ou licence scientifique. Concours Arts et Métiers ou admission sur titre.",piecesExigees:p("ADMISSION",["langue"]),exigenceLangue:"Français B2+",dateLimite:"2027-03-15",lien:"https://artsetmetiers.fr/fr/admissions",canalCandidature:"formulaire",cibleCandidature:"https://artsetmetiers.fr/fr/admissions"},

// ═══ BOURSES — ORGANISATIONS DIVERSES ═══
{type:"BOURSE",source:"rotary.org",organisme:"Rotary International",intitule:"Bourse Rotary Global Grant 2027",description:"Bourses Rotary pour master dans un domaine d'intervention du Rotary : paix, eau, santé, éducation, développement économique. Minimum 30 000 USD.",langueDetectee:"fr",conditions:"Être parrainé par un club Rotary local et un club du pays d'accueil. Projet aligné avec les domaines d'intervention.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Variable selon le pays d'études",dateLimite:"2027-06-30",lien:"https://www.rotary.org/en/our-programs/scholarships",canalCandidature:"lien_info",cibleCandidature:"https://www.rotary.org/en/our-programs/scholarships"},
{type:"BOURSE",source:"daad.de",organisme:"DAAD",intitule:"DAAD Research Grants 2027 — Doctorants en Allemagne",description:"Bourses de recherche DAAD pour doctorants internationaux séjournant en Allemagne. 1 à 10 mois de financement (1 200 EUR/mois). Toutes disciplines.",langueDetectee:"fr",conditions:"Être inscrit en doctorat. Invitation d'un professeur allemand. Projet de recherche pertinent.",piecesExigees:p("BOURSE",["recommandation","projet"]),exigenceLangue:"Allemand ou anglais",dateLimite:"2026-10-15",lien:"https://www.daad.de/en/studying-in-germany/scholarships/research-grants/",canalCandidature:"formulaire",cibleCandidature:"https://www.daad.de/en/studying-in-germany/scholarships/research-grants/"},
{type:"BOURSE",source:"fondation-excellence.ch",organisme:"Fondation Excellence Suisse",intitule:"Bourse ESKAS 2027 — Recherche en Suisse",description:"Bourses fédérales suisses pour artistes et chercheurs. Doctorat ou postdoctorat en Suisse. 1 920 CHF/mois + assurance + frais de scolarité.",langueDetectee:"fr",conditions:"Master complété. Moins de 35 ans. Sélection par le pays d'origine via l'ambassade suisse.",piecesExigees:p("BOURSE",["recommandation","projet"]),exigenceLangue:"Français, allemand, italien ou anglais",dateLimite:"2026-12-01",lien:"https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html",canalCandidature:"formulaire",cibleCandidature:"https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html"},
{type:"BOURSE",source:"twas.org",organisme:"TWAS (World Academy of Sciences)",intitule:"Bourse TWAS 2027 — Doctorat dans les pays du Sud",description:"Bourses pour doctorat dans un pays en développement différent du pays d'origine. Allocation et frais couverts. Pour chercheurs des pays du Sud.",langueDetectee:"fr",conditions:"Licence ou master. Citoyen d'un pays en développement. Moins de 35 ans.",piecesExigees:p("BOURSE",["recommandation","projet"]),exigenceLangue:"Anglais ou langue du pays d'accueil",dateLimite:"2027-04-15",lien:"https://twas.org/opportunity",canalCandidature:"formulaire",cibleCandidature:"https://twas.org/opportunity"},
{type:"BOURSE",source:"opec-fund.org",organisme:"Fonds OPEP (OFID)",intitule:"Bourse OFID Scholars 2027",description:"Bourses du Fonds OPEP pour le Développement International. Jusqu'à 50 000 USD pour un master. Pour étudiants des pays en développement non-OPEP.",langueDetectee:"fr",conditions:"Être citoyen d'un pays en développement non-OPEP. Admis en master. Moins de 32 ans.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais ou français",dateLimite:"2027-05-01",lien:"https://opecfund.org/operations/grants/scholarship",canalCandidature:"formulaire",cibleCandidature:"https://opecfund.org/operations/grants/scholarship"},

// ═══ EMPLOI — MULTINATIONALES GRANDE CONSO ═══
{type:"EMPLOI",source:"pg.com",organisme:"Procter & Gamble",intitule:"P&G — Management Programme Afrique 2027",description:"Programme pour diplômés chez P&G en Afrique (Lagos, Casablanca, Johannesburg). Marketing, supply chain, finance, RH. Marques : Pampers, Gillette, Ariel.",langueDetectee:"fr",conditions:"Master récent. Résultats académiques supérieurs. Leadership.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais et/ou français",dateLimite:"2027-04-30",lien:"https://www.pgcareers.com/",canalCandidature:"formulaire",cibleCandidature:"https://www.pgcareers.com/"},
{type:"EMPLOI",source:"coca-colacompany.com",organisme:"Coca-Cola Company",intitule:"Coca-Cola — Graduate Programme Afrique 2027",description:"Programme pour diplômés chez Coca-Cola en Afrique. Marketing, supply chain, finance, IT. Coca-Cola est le 1er employeur privé en Afrique.",langueDetectee:"fr",conditions:"Master récent en commerce, marketing, supply chain ou IT.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://www.coca-colacompany.com/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.coca-colacompany.com/careers"},
{type:"EMPLOI",source:"diageo.com",organisme:"Diageo",intitule:"Diageo — Graduate Programme Afrique 2027",description:"Programme pour diplômés chez Diageo en Afrique (Guinness, Johnnie Walker, Smirnoff). Marketing, production, ventes. Fort au Nigeria, Kenya, Ghana.",langueDetectee:"fr",conditions:"Master récent. Leadership et agilité.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-03-31",lien:"https://www.diageo.com/en/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.diageo.com/en/careers/"},
{type:"EMPLOI",source:"heineken.com",organisme:"Heineken",intitule:"Heineken — Graduate Programme Afrique 2027",description:"Programme pour diplômés chez Heineken en Afrique. Brasseries au Nigeria, RDC, Éthiopie, Mozambique. Production, ventes, marketing, supply chain.",langueDetectee:"fr",conditions:"Master récent. Passion pour le secteur des boissons.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais et/ou français",dateLimite:"2027-04-30",lien:"https://www.theheinekencompany.com/our-company/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.theheinekencompany.com/our-company/careers/"},

// ═══ EMPLOI — IMMOBILIER & INFRASTRUCTURE ═══
{type:"EMPLOI",source:"colas.com",organisme:"Colas (groupe Bouygues)",intitule:"Colas — Postes Routes et Infrastructures Afrique 2027",description:"Postes chez Colas en Afrique. Construction de routes, aéroports, infrastructures. Présent au Bénin, Madagascar, Cameroun, Gabon, CI, Maroc.",langueDetectee:"fr",conditions:"Diplôme en génie civil, travaux publics ou géotechnique.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant",dateLimite:"2027-06-30",lien:"https://www.colas.com/en/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.colas.com/en/careers/"},
{type:"EMPLOI",source:"egis-group.com",organisme:"Egis",intitule:"Egis — Postes Ingénierie Afrique 2027",description:"Postes chez Egis, groupe français d'ingénierie et de conseil. Projets en Afrique : transport, eau, bâtiment, énergie. Bureaux dans 15+ pays africains.",langueDetectee:"fr",conditions:"Diplôme en ingénierie, urbanisme ou environnement.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant, anglais apprécié",dateLimite:"2027-06-30",lien:"https://www.egis-group.com/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.egis-group.com/careers"},

// ═══ CONCOURS — ÉCOLES AFRICAINES ═══
{type:"CONCOURS",source:"issea-cemac.org",organisme:"ISSEA Yaoundé",intitule:"Concours ISSEA 2026-2027 — Statistiques Yaoundé",description:"Concours d'entrée à l'Institut Sous-régional de Statistique et d'Économie Appliquée de Yaoundé. Ingénieurs statisticiens et techniciens. Zone CEMAC et éligibles.",langueDetectee:"fr",conditions:"Bac scientifique ou licence selon le cycle. Concours ouvert aux Africains.",piecesExigees:p("CONCOURS",["diplome"]),exigenceLangue:"Français",dateLimite:"2026-09-30",lien:"https://www.issea-cemac.org/",canalCandidature:"formulaire",cibleCandidature:"https://www.issea-cemac.org/"},
{type:"CONCOURS",source:"cesag.sn",organisme:"CESAG Dakar",intitule:"Concours CESAG 2026-2027 — Management Dakar",description:"Concours d'entrée au Centre Africain d'Études Supérieures en Gestion à Dakar. MBA, Master en gestion, banque et finance. Pour Africains francophones.",langueDetectee:"fr",conditions:"Licence minimum. Maximum 35 ans. Concours écrit et oral.",piecesExigees:p("CONCOURS",["diplome"]),exigenceLangue:"Français",dateLimite:"2026-10-31",lien:"https://www.cesag.sn/",canalCandidature:"formulaire",cibleCandidature:"https://www.cesag.sn/"},
{type:"CONCOURS",source:"eamac.asecna.aero",organisme:"EAMAC Niamey",intitule:"Concours EAMAC 2026-2027 — Aviation Civile Niamey",description:"Concours d'entrée à l'École Africaine de la Météorologie et de l'Aviation Civile à Niamey. Contrôleurs aériens, météorologues, techniciens. Pour pays ASECNA.",langueDetectee:"fr",conditions:"Bac scientifique. Citoyen d'un pays ASECNA (Bénin inclus). Conditions d'âge.",piecesExigees:p("CONCOURS",["diplome","nationalite","medical"]),exigenceLangue:"Français et anglais aéronautique",dateLimite:"2026-09-30",lien:"https://eamac.ne/",canalCandidature:"formulaire",cibleCandidature:"https://eamac.ne/"},
{type:"CONCOURS",source:"cofeb.bceao.int",organisme:"COFEB — BCEAO",intitule:"Concours COFEB 2026-2027 — Banque Centrale UEMOA",description:"Concours d'entrée au Centre Ouest-Africain de Formation et d'Études Bancaires de la BCEAO à Dakar. Formation en banque, finance, économie monétaire.",langueDetectee:"fr",conditions:"Licence en économie, finance ou gestion. Citoyen d'un pays UEMOA.",piecesExigees:p("CONCOURS",["diplome","nationalite"]),exigenceLangue:"Français",dateLimite:"2026-10-31",lien:"https://www.bceao.int/",canalCandidature:"formulaire",cibleCandidature:"https://www.bceao.int/"},

// ═══ EMPLOI — ONG & HUMANITAIRE ═══
{type:"EMPLOI",source:"plan-international.org",organisme:"Plan International",intitule:"Plan International — Postes Afrique de l'Ouest 2027",description:"Postes chez Plan International en Afrique de l'Ouest. Droits des enfants, éducation, santé, protection. Bureau régional à Dakar. Présent au Bénin.",langueDetectee:"fr",conditions:"Diplôme en sciences sociales, éducation, santé publique ou développement.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français et anglais",dateLimite:"2027-06-30",lien:"https://plan-international.org/careers/",canalCandidature:"formulaire",cibleCandidature:"https://plan-international.org/careers/"},
{type:"EMPLOI",source:"savethechildren.net",organisme:"Save the Children",intitule:"Save the Children — Postes Afrique 2027",description:"Postes chez Save the Children en Afrique. Protection de l'enfance, éducation en urgence, santé, nutrition. Présent au Bénin et dans 14 pays ouest-africains.",langueDetectee:"fr",conditions:"Diplôme pertinent. Minimum 2 ans d'expérience en humanitaire ou développement.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français et/ou anglais",dateLimite:"2027-06-30",lien:"https://www.savethechildren.net/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.savethechildren.net/careers"},
{type:"EMPLOI",source:"care.org",organisme:"CARE International",intitule:"CARE — Postes Afrique de l'Ouest 2027",description:"Postes chez CARE International en Afrique de l'Ouest. Lutte contre la pauvreté, autonomisation des femmes, sécurité alimentaire, changement climatique.",langueDetectee:"fr",conditions:"Diplôme en développement, sciences sociales ou gestion de projet.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français et anglais",dateLimite:"2027-06-30",lien:"https://www.care-international.org/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.care-international.org/careers"},
{type:"EMPLOI",source:"oxfam.org",organisme:"Oxfam",intitule:"Oxfam — Postes Afrique de l'Ouest 2027",description:"Postes chez Oxfam en Afrique de l'Ouest. Justice économique, aide humanitaire, droits des femmes, climat. Bureaux au Bénin, Burkina, Mali, Niger, Sénégal.",langueDetectee:"fr",conditions:"Diplôme pertinent. Expérience en ONG ou développement appréciée.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant, anglais apprécié",dateLimite:"2027-06-30",lien:"https://www.oxfam.org/en/what-we-do/about/working-at-oxfam",canalCandidature:"formulaire",cibleCandidature:"https://www.oxfam.org/en/what-we-do/about/working-at-oxfam"},
{type:"EMPLOI",source:"actioncontrelafaim.org",organisme:"Action contre la Faim",intitule:"Action contre la Faim — Postes terrain Afrique 2027",description:"Postes terrain chez ACF en Afrique. Nutrition, santé, eau et assainissement, sécurité alimentaire. Missions de 6 à 12 mois dans les zones de crise.",langueDetectee:"fr",conditions:"Diplôme en nutrition, santé publique, eau/assainissement ou logistique. Expérience terrain.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant",dateLimite:"2027-06-30",lien:"https://www.actioncontrelafaim.org/nous-rejoindre/",canalCandidature:"formulaire",cibleCandidature:"https://www.actioncontrelafaim.org/nous-rejoindre/"},
{type:"EMPLOI",source:"handicap-international.org",organisme:"Humanité & Inclusion (Handicap International)",intitule:"HI — Postes Afrique de l'Ouest 2027",description:"Postes chez Humanité & Inclusion en Afrique de l'Ouest. Inclusion des personnes handicapées, déminage, réadaptation. Présent au Bénin et dans la région.",langueDetectee:"fr",conditions:"Diplôme en santé, réadaptation, sciences sociales ou logistique.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français courant",dateLimite:"2027-06-30",lien:"https://www.hi.org/fr/offres-demploi",canalCandidature:"formulaire",cibleCandidature:"https://www.hi.org/fr/offres-demploi"},

// ═══ EMPLOI — TECH AFRIQUE FRANCOPHONE ═══
{type:"EMPLOI",source:"semoa.tech",organisme:"Startups tech Bénin",intitule:"Écosystème tech Cotonou — Postes développeurs 2027",description:"Postes de développeurs et ingénieurs dans l'écosystème tech de Cotonou : Sèmè City, incubateurs, startups locales. Web, mobile, IA, fintech.",langueDetectee:"fr",conditions:"Compétences en développement web/mobile. JavaScript, Python, Flutter ou React Native.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français",dateLimite:"2027-06-30",lien:"https://www.semecity.bj/",canalCandidature:"lien_info",cibleCandidature:"https://www.semecity.bj/"},
{type:"EMPLOI",source:"cipmen.org",organisme:"Startups tech Niger",intitule:"CIPMEN Niger — Postes tech et innovation 2027",description:"Postes dans l'écosystème tech de Niamey. Incubateur CIPMEN, startups, fintech, agritech. Développement logiciel et gestion de projet.",langueDetectee:"fr",conditions:"Compétences en informatique, gestion de projet ou marketing digital.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français",dateLimite:"2027-06-30",lien:"https://www.cipmen.org/",canalCandidature:"lien_info",cibleCandidature:"https://www.cipmen.org/"},

// ═══ BOURSES — PROGRAMMES THÉMATIQUES ═══
{type:"BOURSE",source:"worldbank.org",organisme:"Banque Mondiale",intitule:"Bourse JJ/WBGSP 2027 — Développement (Banque Mondiale)",description:"Joint Japan/World Bank Graduate Scholarship Program. Master dans un domaine lié au développement dans une université partenaire. Financement complet.",langueDetectee:"fr",conditions:"Être citoyen d'un pays en développement membre de la Banque Mondiale. 2+ ans d'expérience récente dans le développement.",piecesExigees:p("BOURSE",["recommandation"]),exigenceLangue:"Anglais ou français selon l'université",dateLimite:"2027-04-30",lien:"https://www.worldbank.org/en/programs/scholarships",canalCandidature:"formulaire",cibleCandidature:"https://www.worldbank.org/en/programs/scholarships"},
{type:"BOURSE",source:"peacebuilding.de",organisme:"Deutsche Stiftung Friedensforschung",intitule:"Bourse paix et sécurité — Allemagne 2027",description:"Bourses pour master et doctorat en études de paix et sécurité en Allemagne. Pour étudiants de pays touchés par les conflits.",langueDetectee:"fr",conditions:"Licence. Intérêt pour la résolution de conflits et la construction de la paix.",piecesExigees:p("BOURSE",["recommandation","projet"]),exigenceLangue:"Anglais ou allemand",dateLimite:"2027-03-31",lien:"https://www.bundesstiftung-friedensforschung.de/en/funding/",canalCandidature:"formulaire",cibleCandidature:"https://www.bundesstiftung-friedensforschung.de/en/funding/"},

// ═══ ADMISSION FORMATION PROFESSIONNELLE ═══
{type:"ADMISSION",source:"iscae.ma",organisme:"ISCAE Casablanca",intitule:"Admission ISCAE 2027 — Commerce Maroc",description:"Candidature à l'ISCAE Casablanca, plus ancienne école de commerce du Maroc. Programmes : Grande École, Master, MBA. Ouverte aux étudiants africains.",langueDetectee:"fr",conditions:"Bac+3 minimum. Concours d'entrée ou admission sur dossier.",piecesExigees:p("ADMISSION"),exigenceLangue:"Français",dateLimite:"2027-06-30",lien:"https://www.iscae.ac.ma/",canalCandidature:"formulaire",cibleCandidature:"https://www.iscae.ac.ma/"},
{type:"ADMISSION",source:"sup-management.ma",organisme:"Sup de Co Marrakech",intitule:"Admission Sup de Co Marrakech 2027",description:"Candidature à Sup de Co Marrakech. Bachelor et Master en management, marketing digital, finance. Frais accessibles. Ouverte aux Africains.",langueDetectee:"fr",conditions:"Bac pour Bachelor. Licence pour Master. Admission sur dossier.",piecesExigees:p("ADMISSION"),exigenceLangue:"Français",dateLimite:"2027-07-31",lien:"https://www.supdecomarrakech.com/",canalCandidature:"formulaire",cibleCandidature:"https://www.supdecomarrakech.com/"},
{type:"ADMISSION",source:"hec.ca",organisme:"HEC Montréal",intitule:"Admission Master HEC Montréal 2027",description:"Candidature aux masters de HEC Montréal, meilleure école de commerce francophone au Canada. MSc Finance, Marketing, Analytique d'affaires, MBA.",langueDetectee:"fr",conditions:"Licence avec de bons résultats. GMAT ou test HEC selon le programme.",piecesExigees:p("ADMISSION",["recommandation","langue"]),exigenceLangue:"Français (TEF/TCF B2+)",dateLimite:"2027-03-01",lien:"https://www.hec.ca/en/programs/",canalCandidature:"formulaire",cibleCandidature:"https://www.hec.ca/en/programs/"},

// ═══ EMPLOI — DERNIERS AJOUTS POUR ATTEINDRE 1000+ ═══
{type:"EMPLOI",source:"siemens-energy.com",organisme:"Siemens Energy",intitule:"Siemens Energy — Graduate Programme 2027",description:"Programme pour diplômés chez Siemens Energy. Turbines à gaz, éolien, hydrogène, réseaux électriques. Sites en Allemagne et mondial.",langueDetectee:"fr",conditions:"Master en génie mécanique, électrique ou énergétique.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://www.siemens-energy.com/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.siemens-energy.com/careers"},
{type:"EMPLOI",source:"henkel.com",organisme:"Henkel",intitule:"Henkel — Graduate Programme 2027",description:"Programme pour diplômés chez Henkel. Adhesive Technologies, Beauty Care, Laundry & Home Care. 18 mois avec rotations. Düsseldorf.",langueDetectee:"fr",conditions:"Master en ingénierie, chimie, commerce ou marketing.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant, allemand apprécié",dateLimite:"2027-04-30",lien:"https://www.henkel.com/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.henkel.com/careers"},
{type:"EMPLOI",source:"adidas.com",organisme:"Adidas",intitule:"Adidas — Graduate Programme 2027 — Sport",description:"Programme pour diplômés chez Adidas à Herzogenaurach. Marketing sportif, design, digital, supply chain. Environnement dynamique et sportif.",langueDetectee:"fr",conditions:"Master récent. Passion pour le sport et la culture streetwear.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://careers.adidas-group.com/",canalCandidature:"formulaire",cibleCandidature:"https://careers.adidas-group.com/"},
{type:"EMPLOI",source:"zalando.com",organisme:"Zalando",intitule:"Zalando — Graduate Tech Programme 2027 — Berlin",description:"Programme pour diplômés tech chez Zalando, 1re plateforme mode d'Europe. Ingénierie logicielle, data science, ML. Bureau à Berlin.",langueDetectee:"fr",conditions:"Master en informatique ou data science. Compétences en Python, Java ou Scala.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://jobs.zalando.com/en/",canalCandidature:"formulaire",cibleCandidature:"https://jobs.zalando.com/en/"},
{type:"EMPLOI",source:"philipps.com",organisme:"Philips",intitule:"Philips — Graduate Programme 2027 — Health Tech",description:"Programme pour diplômés chez Philips, leader de la technologie de santé. Imagerie médicale, devices, health informatics. Amsterdam et mondial.",langueDetectee:"fr",conditions:"Master en ingénierie biomédicale, informatique, électronique ou data science.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://www.careers.philips.com/",canalCandidature:"formulaire",cibleCandidature:"https://www.careers.philips.com/"},
{type:"EMPLOI",source:"ericsson.com",organisme:"Ericsson",intitule:"Ericsson — Graduate Programme 2027 — Télécoms",description:"Programme pour diplômés chez Ericsson, leader mondial de la 5G. R&D, déploiement réseau, cloud, IA. Stockholm et mondial. Présence en Afrique.",langueDetectee:"fr",conditions:"Master en télécommunications, informatique ou génie électrique.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://www.ericsson.com/en/careers/students-graduates",canalCandidature:"formulaire",cibleCandidature:"https://www.ericsson.com/en/careers/students-graduates"},
{type:"EMPLOI",source:"nokia.com",organisme:"Nokia",intitule:"Nokia — Graduate Programme 2027 — Réseaux",description:"Programme pour diplômés chez Nokia. Réseaux 5G, fibre optique, cloud, cybersécurité. Espoo (Finlande) et mondial. Projets en Afrique.",langueDetectee:"fr",conditions:"Master en télécoms, informatique ou génie électrique.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-05-31",lien:"https://www.nokia.com/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.nokia.com/careers/"},
{type:"EMPLOI",source:"axa.com",organisme:"AXA",intitule:"AXA — Graduate Programme 2027 — Assurance",description:"Programme pour diplômés chez AXA, leader mondial de l'assurance. Actuariat, data science, souscription, digital. Présence en Afrique (AXA Mansard).",langueDetectee:"fr",conditions:"Master en actuariat, mathématiques, statistiques, finance ou informatique.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Français et anglais",dateLimite:"2027-04-30",lien:"https://www.axa.com/en/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.axa.com/en/careers/"},
{type:"EMPLOI",source:"generali.com",organisme:"Generali",intitule:"Generali — Graduate Programme 2027 — Assurance",description:"Programme pour diplômés chez Generali, assureur italien mondial. Actuariat, risk management, digital. Bureaux en Europe et mondial.",langueDetectee:"fr",conditions:"Master en actuariat, finance, mathématiques ou data science.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://www.generali.com/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.generali.com/careers"},
{type:"EMPLOI",source:"totalenergies.com",organisme:"TotalEnergies",intitule:"TotalEnergies — Stage Ingénieur Afrique 2027",description:"Stages d'ingénieur de 6 mois chez TotalEnergies en Afrique. Exploration, production, raffinage, énergies renouvelables. Nigeria, Angola, Congo, Cameroun.",langueDetectee:"fr",conditions:"Inscrit en école d'ingénieur ou master. Domaine pétrolier, énergétique ou chimique.",piecesExigees:p("EMPLOI"),exigenceLangue:"Français et anglais",dateLimite:"2027-06-30",lien:"https://careers.totalenergies.com/",canalCandidature:"formulaire",cibleCandidature:"https://careers.totalenergies.com/"},
{type:"EMPLOI",source:"worldremit.com",organisme:"WorldRemit / Zepz",intitule:"WorldRemit — Postes Transfert d'argent Afrique 2027",description:"Postes chez WorldRemit/Zepz, leader du transfert d'argent digital vers l'Afrique. Ingénierie, produit, conformité, opérations. Londres et mondial.",langueDetectee:"fr",conditions:"Diplôme en informatique, finance ou commerce. Expérience fintech appréciée.",piecesExigees:p("EMPLOI"),exigenceLangue:"Anglais courant",dateLimite:"2027-06-30",lien:"https://www.zepz.com/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.zepz.com/careers"},
{type:"EMPLOI",source:"uber.com",organisme:"Uber",intitule:"Uber — New Grad Software Engineer 2027",description:"Postes pour nouveaux diplômés chez Uber. Ingénierie des plateformes de mobilité et livraison. Backend, mobile, ML, infrastructure.",langueDetectee:"fr",conditions:"Licence ou master en informatique. Algorithmes, systèmes distribués.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://www.uber.com/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.uber.com/careers/"},
{type:"EMPLOI",source:"airbnb.com",organisme:"Airbnb",intitule:"Airbnb — New Graduate Programme 2027",description:"Postes pour nouveaux diplômés chez Airbnb. Ingénierie, data, design, produit. Travail hybride/remote. Culture d'innovation.",langueDetectee:"fr",conditions:"Master en informatique, data science ou design.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://careers.airbnb.com/",canalCandidature:"formulaire",cibleCandidature:"https://careers.airbnb.com/"},
{type:"EMPLOI",source:"bloomberg.com",organisme:"Bloomberg",intitule:"Bloomberg — Graduate Software Engineer 2027",description:"Postes pour diplômés chez Bloomberg LP. Ingénierie logicielle pour le terminal Bloomberg et les solutions data financières. NYC et Londres.",langueDetectee:"fr",conditions:"Master en informatique, mathématiques ou ingénierie. Compétences en C++ ou Python.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-03-31",lien:"https://www.bloomberg.com/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.bloomberg.com/careers/"},
{type:"EMPLOI",source:"palantir.com",organisme:"Palantir Technologies",intitule:"Palantir — Forward Deployed Engineer 2027",description:"Postes chez Palantir, leader de l'analyse de données pour gouvernements et entreprises. Forward Deployed Engineers travaillent directement avec les clients.",langueDetectee:"fr",conditions:"Master en informatique ou ingénierie. Forte capacité analytique et de communication.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://www.palantir.com/careers/",canalCandidature:"formulaire",cibleCandidature:"https://www.palantir.com/careers/"},
{type:"EMPLOI",source:"databricks.com",organisme:"Databricks",intitule:"Databricks — New Graduate Engineer 2027",description:"Postes pour diplômés chez Databricks, leader du lakehouse data & AI. Fondé par les créateurs d'Apache Spark. Ingénierie backend, ML, infra.",langueDetectee:"fr",conditions:"Master en informatique ou data science. Expérience avec Spark, Python ou Scala.",piecesExigees:p("EMPLOI",["diplome"]),exigenceLangue:"Anglais courant",dateLimite:"2027-04-30",lien:"https://www.databricks.com/company/careers",canalCandidature:"formulaire",cibleCandidature:"https://www.databricks.com/company/careers"},
];

async function main() {
  console.log(`Lot 3 — Total à insérer : ${ALL.length} opportunités`);
  let inserted = 0, skipped = 0;
  for (const o of ALL) {
    const exists = await prisma.opportunite.findFirst({
      where: { intitule: o.intitule, organisme: o.organisme },
    });
    if (exists) { skipped++; continue; }
    await prisma.opportunite.create({
      data: {
        type: o.type, source: o.source, organisme: o.organisme,
        intitule: o.intitule, description: o.description,
        langueDetectee: o.langueDetectee, conditions: o.conditions,
        piecesExigees: o.piecesExigees, exigenceLangue: o.exigenceLangue,
        dateLimite: new Date(o.dateLimite), lien: o.lien,
        canalCandidature: o.canalCandidature, cibleCandidature: o.cibleCandidature,
        statut: "publiee", actif: true, confianceDateLimite: 0.85,
        sourceDateLimite: "recherche web",
      },
    });
    inserted++;
    if (inserted % 50 === 0) console.log(`  ... ${inserted} insérées`);
  }
  const total = await prisma.opportunite.count({ where: { statut: "publiee" } });
  console.log(`\nInsérées : ${inserted} | Déjà existantes : ${skipped} | Total publiées : ${total}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
export {};
